/***************************************************************************//**
* \file ITSI_AM_LSTM_tflm_model_int16x8.h
*
* \brief
* Autogenerated with ml-coretools, this file contains ITSI_AM_LSTM model data.
* Date: 2025-02-19 19:23:31.243190
*******************************************************************************
* \copyright
* Copyright 2025, Cypress Semiconductor Corporation (an Infineon company).
* All rights reserved.
* You may use this file only in accordance with the license, terms, conditions,
* disclaimers, and limitations in the end user license agreement accompanying
* the software package with which this file was provided.
******************************************************************************/

/*
ml-coretools 3.0.0 based on TensorFlow 2.15.0 and ethos-u-vela 3.11.0
    ml-coretools-middleware-streaming 3.0.0
    ml-coretools-tflm-qemu-images 3.0.0.14704
*/

#ifndef ITSI_AM_LSTM_TFLM_MODEL_INT16X8_H
#define ITSI_AM_LSTM_TFLM_MODEL_INT16X8_H

#include <stdint.h>


#ifdef CY_ML_MODEL_MEM
extern const uint8_t ITSI_AM_LSTM_model_bin[];
#else
extern uint8_t ITSI_AM_LSTM_model_bin[];
#endif // CY_ML_MODEL_MEM
#define ITSI_AM_LSTM_MODEL_BIN_LEN (218096u)
#define ITSI_AM_LSTM_ARENA_SIZE (18432u)

#endif // ITSI_AM_LSTM_TFLM_MODEL_INT16X8_H

