/***************************************************************************//**
* \file ITSI_AM_INT8_tflm_model_int8x8.h
*
* \brief
* Autogenerated with ml-coretools, this file contains ITSI_AM_INT8 model data.
* Date: 2024-12-03 16:04:40.607332
*******************************************************************************
* \copyright
* Copyright 2024, Cypress Semiconductor Corporation (an Infineon company).
* All rights reserved.
* You may use this file only in accordance with the license, terms, conditions,
* disclaimers, and limitations in the end user license agreement accompanying
* the software package with which this file was provided.
******************************************************************************/

/*
ml-coretools 3.0.0.8266 based on TensorFlow 2.15.0 and ethos-u-vela 3.11.0
    ml-coretools-middleware-streaming 3.0.0.13330
    ml-coretools-tflm-qemu-images 3.0.0.13330
*/

#ifndef ITSI_AM_INT8_TFLM_MODEL_INT8X8_H
#define ITSI_AM_INT8_TFLM_MODEL_INT8X8_H

#include <stdint.h>


#ifdef CY_ML_MODEL_MEM
extern const uint8_t ITSI_AM_INT8_model_bin[];
#else
extern uint8_t ITSI_AM_INT8_model_bin[];
#endif // CY_ML_MODEL_MEM
#define ITSI_AM_INT8_MODEL_BIN_LEN (477152u)
#define ITSI_AM_INT8_ARENA_SIZE (16384u)

#endif // ITSI_AM_INT8_TFLM_MODEL_INT8X8_H

