/* This file is automatically generated. */
#ifndef CYCFG_MPC_H
#define CYCFG_MPC_H
#include <stdbool.h>
#include <stdint.h>
#include "cy_device.h"
#include "cy_mpc.h"


/** MPC region configuration structure */
typedef struct {
    MPC_Type*          base;          /**< Address of the MPC controller */
    uint32_t           offset;        /**< Region offset within block */
    uint32_t           size;          /**< Region size */
    cy_en_mpc_size_t   regionSize;    /**< MPC protection region size */
    uint32_t           ns_mask;       /**< NS bit mask for each PC */
    uint32_t           r_mask;        /**< R  bit mask for each PC */
    uint32_t           w_mask;        /**< W  bit mask for each PC */
} cy_mpc_regions_config_2_t;


/** Full MPC settings structure */
typedef struct {
    const cy_mpc_regions_config_2_t* config;    /**< Pointer to the settings array */
    uint8_t size;                               /**< Array size */
    bool response;                              /**< MPC response on access violation */
} cy_complete_mpc_config_t;

#endif /* #ifndef CYCFG_MPC_H */
