/*******************************************************************************
 * File Name: cycfg_pins.h
 *
 * Description:
 * Pin configuration
 * This file was automatically generated and should not be modified.
 * Configurator Backend 3.50.0
 * device-db 4.5.30.8214
 * mtb-device-support-pse8xxgp 1.0.200.195
 *
 *******************************************************************************
 * Copyright 2025 Cypress Semiconductor Corporation (an Infineon company) or
 * an affiliate of Cypress Semiconductor Corporation.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ******************************************************************************/

#if !defined(CYCFG_PINS_H)
#define CYCFG_PINS_H

#include "cycfg_notices.h"
#include "cy_gpio.h"
#include "cycfg_routing.h"

#if defined (CY_USING_HAL)
#include "cyhal_hwmgr.h"
#endif /* defined (CY_USING_HAL) */

#if defined (CY_USING_HAL_LITE)
#include "cyhal_hw_types.h"
#endif /* defined (CY_USING_HAL_LITE) */

#if defined(__cplusplus)
extern "C" {
#endif /* defined(__cplusplus) */

#define CYBSP_RS_SPI_SS_ENABLED 1U
#define CYBSP_RS_SPI_SS_PORT GPIO_PRT0
#define CYBSP_RS_SPI_SS_PORT_NUM 0U
#define CYBSP_RS_SPI_SS_PIN 0U
#define CYBSP_RS_SPI_SS_NUM 0U
#define CYBSP_RS_SPI_SS_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define CYBSP_RS_SPI_SS_INIT_DRIVESTATE 1
#ifndef ioss_0_port_0_pin_0_HSIOM
    #define ioss_0_port_0_pin_0_HSIOM HSIOM_SEL_GPIO
#endif
#define CYBSP_RS_SPI_SS_HSIOM ioss_0_port_0_pin_0_HSIOM
#define CYBSP_RS_SPI_SS_IRQ ioss_interrupts_gpio_0_IRQn

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
#define CYBSP_RS_SPI_SS_HAL_PORT_PIN P0_0
#define CYBSP_RS_SPI_SS P0_0
#define CYBSP_RS_SPI_SS_HAL_IRQ CYHAL_GPIO_IRQ_NONE
#define CYBSP_RS_SPI_SS_HAL_DIR CYHAL_GPIO_DIR_OUTPUT 
#define CYBSP_RS_SPI_SS_HAL_DRIVEMODE CYHAL_GPIO_DRIVE_STRONG
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

#define CYBSP_OSPI_RAM_SS_ENABLED 1U
#define CYBSP_OSPI_RAM_SS_PORT GPIO_PRT0
#define CYBSP_OSPI_RAM_SS_PORT_NUM 0U
#define CYBSP_OSPI_RAM_SS_PIN 1U
#define CYBSP_OSPI_RAM_SS_NUM 1U
#define CYBSP_OSPI_RAM_SS_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define CYBSP_OSPI_RAM_SS_INIT_DRIVESTATE 1
#ifndef ioss_0_port_0_pin_1_HSIOM
    #define ioss_0_port_0_pin_1_HSIOM HSIOM_SEL_GPIO
#endif
#define CYBSP_OSPI_RAM_SS_HSIOM ioss_0_port_0_pin_1_HSIOM
#define CYBSP_OSPI_RAM_SS_IRQ ioss_interrupts_gpio_0_IRQn

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
#define CYBSP_OSPI_RAM_SS_HAL_PORT_PIN P0_1
#define CYBSP_OSPI_RAM_SS P0_1
#define CYBSP_OSPI_RAM_SS_HAL_IRQ CYHAL_GPIO_IRQ_NONE
#define CYBSP_OSPI_RAM_SS_HAL_DIR CYHAL_GPIO_DIR_OUTPUT 
#define CYBSP_OSPI_RAM_SS_HAL_DRIVEMODE CYHAL_GPIO_DRIVE_STRONG
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

#define CYBSP_BT_UART_RX_ENABLED 1U
#define CYBSP_BT_UART_RX_PORT GPIO_PRT10
#define CYBSP_BT_UART_RX_PORT_NUM 10U
#define CYBSP_BT_UART_RX_PIN 0U
#define CYBSP_BT_UART_RX_NUM 0U
#define CYBSP_BT_UART_RX_DRIVEMODE CY_GPIO_DM_HIGHZ
#define CYBSP_BT_UART_RX_INIT_DRIVESTATE 1
#ifndef ioss_0_port_10_pin_0_HSIOM
    #define ioss_0_port_10_pin_0_HSIOM HSIOM_SEL_GPIO
#endif
#define CYBSP_BT_UART_RX_HSIOM ioss_0_port_10_pin_0_HSIOM
#define CYBSP_BT_UART_RX_IRQ ioss_interrupts_gpio_10_IRQn

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
#define CYBSP_BT_UART_RX_HAL_PORT_PIN P10_0
#define CYBSP_BT_UART_RX P10_0
#define CYBSP_BT_UART_RX_HAL_IRQ CYHAL_GPIO_IRQ_NONE
#define CYBSP_BT_UART_RX_HAL_DIR CYHAL_GPIO_DIR_INPUT 
#define CYBSP_BT_UART_RX_HAL_DRIVEMODE CYHAL_GPIO_DRIVE_NONE
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

#define CYBSP_BT_UART_TX_ENABLED 1U
#define CYBSP_BT_UART_TX_PORT GPIO_PRT10
#define CYBSP_BT_UART_TX_PORT_NUM 10U
#define CYBSP_BT_UART_TX_PIN 1U
#define CYBSP_BT_UART_TX_NUM 1U
#define CYBSP_BT_UART_TX_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define CYBSP_BT_UART_TX_INIT_DRIVESTATE 1
#ifndef ioss_0_port_10_pin_1_HSIOM
    #define ioss_0_port_10_pin_1_HSIOM HSIOM_SEL_GPIO
#endif
#define CYBSP_BT_UART_TX_HSIOM ioss_0_port_10_pin_1_HSIOM
#define CYBSP_BT_UART_TX_IRQ ioss_interrupts_gpio_10_IRQn

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
#define CYBSP_BT_UART_TX_HAL_PORT_PIN P10_1
#define CYBSP_BT_UART_TX P10_1
#define CYBSP_BT_UART_TX_HAL_IRQ CYHAL_GPIO_IRQ_NONE
#define CYBSP_BT_UART_TX_HAL_DIR CYHAL_GPIO_DIR_OUTPUT 
#define CYBSP_BT_UART_TX_HAL_DRIVEMODE CYHAL_GPIO_DRIVE_STRONG
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

#define CYBSP_BT_UART_CTS_ENABLED 1U
#define CYBSP_BT_UART_CTS_PORT GPIO_PRT10
#define CYBSP_BT_UART_CTS_PORT_NUM 10U
#define CYBSP_BT_UART_CTS_PIN 2U
#define CYBSP_BT_UART_CTS_NUM 2U
#define CYBSP_BT_UART_CTS_DRIVEMODE CY_GPIO_DM_HIGHZ
#define CYBSP_BT_UART_CTS_INIT_DRIVESTATE 0
#ifndef ioss_0_port_10_pin_2_HSIOM
    #define ioss_0_port_10_pin_2_HSIOM HSIOM_SEL_GPIO
#endif
#define CYBSP_BT_UART_CTS_HSIOM ioss_0_port_10_pin_2_HSIOM
#define CYBSP_BT_UART_CTS_IRQ ioss_interrupts_gpio_10_IRQn

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
#define CYBSP_BT_UART_CTS_HAL_PORT_PIN P10_2
#define CYBSP_BT_UART_CTS P10_2
#define CYBSP_BT_UART_CTS_HAL_IRQ CYHAL_GPIO_IRQ_NONE
#define CYBSP_BT_UART_CTS_HAL_DIR CYHAL_GPIO_DIR_INPUT 
#define CYBSP_BT_UART_CTS_HAL_DRIVEMODE CYHAL_GPIO_DRIVE_NONE
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

#define CYBSP_BT_UART_RTS_ENABLED 1U
#define CYBSP_BT_UART_RTS_PORT GPIO_PRT10
#define CYBSP_BT_UART_RTS_PORT_NUM 10U
#define CYBSP_BT_UART_RTS_PIN 3U
#define CYBSP_BT_UART_RTS_NUM 3U
#define CYBSP_BT_UART_RTS_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define CYBSP_BT_UART_RTS_INIT_DRIVESTATE 0
#ifndef ioss_0_port_10_pin_3_HSIOM
    #define ioss_0_port_10_pin_3_HSIOM HSIOM_SEL_GPIO
#endif
#define CYBSP_BT_UART_RTS_HSIOM ioss_0_port_10_pin_3_HSIOM
#define CYBSP_BT_UART_RTS_IRQ ioss_interrupts_gpio_10_IRQn

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
#define CYBSP_BT_UART_RTS_HAL_PORT_PIN P10_3
#define CYBSP_BT_UART_RTS P10_3
#define CYBSP_BT_UART_RTS_HAL_IRQ CYHAL_GPIO_IRQ_NONE
#define CYBSP_BT_UART_RTS_HAL_DIR CYHAL_GPIO_DIR_OUTPUT 
#define CYBSP_BT_UART_RTS_HAL_DRIVEMODE CYHAL_GPIO_DRIVE_STRONG
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

#define CYBSP_BT_HOST_WAKE_ENABLED 1U
#define CYBSP_BT_HOST_WAKE_PORT GPIO_PRT10
#define CYBSP_BT_HOST_WAKE_PORT_NUM 10U
#define CYBSP_BT_HOST_WAKE_PIN 4U
#define CYBSP_BT_HOST_WAKE_NUM 4U
#define CYBSP_BT_HOST_WAKE_DRIVEMODE CY_GPIO_DM_HIGHZ
#define CYBSP_BT_HOST_WAKE_INIT_DRIVESTATE 0
#ifndef ioss_0_port_10_pin_4_HSIOM
    #define ioss_0_port_10_pin_4_HSIOM HSIOM_SEL_GPIO
#endif
#define CYBSP_BT_HOST_WAKE_HSIOM ioss_0_port_10_pin_4_HSIOM
#define CYBSP_BT_HOST_WAKE_IRQ ioss_interrupts_gpio_10_IRQn

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
#define CYBSP_BT_HOST_WAKE_HAL_PORT_PIN P10_4
#define CYBSP_BT_HOST_WAKE P10_4
#define CYBSP_BT_HOST_WAKE_HAL_IRQ CYHAL_GPIO_IRQ_NONE
#define CYBSP_BT_HOST_WAKE_HAL_DIR CYHAL_GPIO_DIR_INPUT 
#define CYBSP_BT_HOST_WAKE_HAL_DRIVEMODE CYHAL_GPIO_DRIVE_NONE
#define CYBSP_INT_CO2 (P10_5)
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

#define CYBSP_BT_DEVICE_WAKE_ENABLED 1U
#define CYBSP_BT_DEVICE_WAKE_PORT GPIO_PRT10
#define CYBSP_BT_DEVICE_WAKE_PORT_NUM 10U
#define CYBSP_BT_DEVICE_WAKE_PIN 6U
#define CYBSP_BT_DEVICE_WAKE_NUM 6U
#define CYBSP_BT_DEVICE_WAKE_DRIVEMODE CY_GPIO_DM_STRONG
#define CYBSP_BT_DEVICE_WAKE_INIT_DRIVESTATE 0
#ifndef ioss_0_port_10_pin_6_HSIOM
    #define ioss_0_port_10_pin_6_HSIOM HSIOM_SEL_GPIO
#endif
#define CYBSP_BT_DEVICE_WAKE_HSIOM ioss_0_port_10_pin_6_HSIOM
#define CYBSP_BT_DEVICE_WAKE_IRQ ioss_interrupts_gpio_10_IRQn

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
#define CYBSP_BT_DEVICE_WAKE_HAL_PORT_PIN P10_6
#define CYBSP_BT_DEVICE_WAKE P10_6
#define CYBSP_BT_DEVICE_WAKE_HAL_IRQ CYHAL_GPIO_IRQ_NONE
#define CYBSP_BT_DEVICE_WAKE_HAL_DIR CYHAL_GPIO_DIR_BIDIRECTIONAL 
#define CYBSP_BT_DEVICE_WAKE_HAL_DRIVEMODE CYHAL_GPIO_DRIVE_STRONG
#define CYBSP_DISP_INT (P10_7)
#define CYBSP_DVP_CAM_DATA0 (P11_0)
#define CYBSP_DVP_CAM_DATA1 (P11_1)
#define CYBSP_DVP_CAM_DATA2 (P11_2)
#define CYBSP_DVP_CAM_DATA3 (P11_3)
#define CYBSP_DVP_CAM_DATA4 (P11_4)
#define CYBSP_DVP_CAM_DATA5 (P11_5)
#define CYBSP_DVP_CAM_DATA6 (P11_6)
#define CYBSP_DVP_CAM_DATA7 (P11_7)
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

#define CYBSP_WIFI_SDIO_CLK_ENABLED 1U
#define CYBSP_WIFI_SDIO_CLK_PORT GPIO_PRT12
#define CYBSP_WIFI_SDIO_CLK_PORT_NUM 12U
#define CYBSP_WIFI_SDIO_CLK_PIN 0U
#define CYBSP_WIFI_SDIO_CLK_NUM 0U
#define CYBSP_WIFI_SDIO_CLK_DRIVEMODE CY_GPIO_DM_STRONG
#define CYBSP_WIFI_SDIO_CLK_INIT_DRIVESTATE 1
#ifndef ioss_0_port_12_pin_0_HSIOM
    #define ioss_0_port_12_pin_0_HSIOM HSIOM_SEL_GPIO
#endif
#define CYBSP_WIFI_SDIO_CLK_HSIOM ioss_0_port_12_pin_0_HSIOM
#define CYBSP_WIFI_SDIO_CLK_IRQ ioss_interrupts_gpio_12_IRQn

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
#define CYBSP_WIFI_SDIO_CLK_HAL_PORT_PIN P12_0
#define CYBSP_WIFI_SDIO_CLK P12_0
#define CYBSP_WIFI_SDIO_CLK_HAL_IRQ CYHAL_GPIO_IRQ_NONE
#define CYBSP_WIFI_SDIO_CLK_HAL_DIR CYHAL_GPIO_DIR_BIDIRECTIONAL 
#define CYBSP_WIFI_SDIO_CLK_HAL_DRIVEMODE CYHAL_GPIO_DRIVE_STRONG
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

#define CYBSP_WIFI_SDIO_D0_ENABLED 1U
#define CYBSP_WIFI_SDIO_D0_PORT GPIO_PRT12
#define CYBSP_WIFI_SDIO_D0_PORT_NUM 12U
#define CYBSP_WIFI_SDIO_D0_PIN 1U
#define CYBSP_WIFI_SDIO_D0_NUM 1U
#define CYBSP_WIFI_SDIO_D0_DRIVEMODE CY_GPIO_DM_STRONG
#define CYBSP_WIFI_SDIO_D0_INIT_DRIVESTATE 1
#ifndef ioss_0_port_12_pin_1_HSIOM
    #define ioss_0_port_12_pin_1_HSIOM HSIOM_SEL_GPIO
#endif
#define CYBSP_WIFI_SDIO_D0_HSIOM ioss_0_port_12_pin_1_HSIOM
#define CYBSP_WIFI_SDIO_D0_IRQ ioss_interrupts_gpio_12_IRQn

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
#define CYBSP_WIFI_SDIO_D0_HAL_PORT_PIN P12_1
#define CYBSP_WIFI_SDIO_D0 P12_1
#define CYBSP_WIFI_SDIO_D0_HAL_IRQ CYHAL_GPIO_IRQ_NONE
#define CYBSP_WIFI_SDIO_D0_HAL_DIR CYHAL_GPIO_DIR_BIDIRECTIONAL 
#define CYBSP_WIFI_SDIO_D0_HAL_DRIVEMODE CYHAL_GPIO_DRIVE_STRONG
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

#define CYBSP_WIFI_SDIO_D1_ENABLED 1U
#define CYBSP_WIFI_SDIO_D1_PORT GPIO_PRT12
#define CYBSP_WIFI_SDIO_D1_PORT_NUM 12U
#define CYBSP_WIFI_SDIO_D1_PIN 2U
#define CYBSP_WIFI_SDIO_D1_NUM 2U
#define CYBSP_WIFI_SDIO_D1_DRIVEMODE CY_GPIO_DM_STRONG
#define CYBSP_WIFI_SDIO_D1_INIT_DRIVESTATE 1
#ifndef ioss_0_port_12_pin_2_HSIOM
    #define ioss_0_port_12_pin_2_HSIOM HSIOM_SEL_GPIO
#endif
#define CYBSP_WIFI_SDIO_D1_HSIOM ioss_0_port_12_pin_2_HSIOM
#define CYBSP_WIFI_SDIO_D1_IRQ ioss_interrupts_gpio_12_IRQn

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
#define CYBSP_WIFI_SDIO_D1_HAL_PORT_PIN P12_2
#define CYBSP_WIFI_SDIO_D1 P12_2
#define CYBSP_WIFI_SDIO_D1_HAL_IRQ CYHAL_GPIO_IRQ_NONE
#define CYBSP_WIFI_SDIO_D1_HAL_DIR CYHAL_GPIO_DIR_BIDIRECTIONAL 
#define CYBSP_WIFI_SDIO_D1_HAL_DRIVEMODE CYHAL_GPIO_DRIVE_STRONG
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

#define CYBSP_I2S_TX_FSYNC_ENABLED 1U
#define CYBSP_I2S_TX_FSYNC_PORT GPIO_PRT12
#define CYBSP_I2S_TX_FSYNC_PORT_NUM 12U
#define CYBSP_I2S_TX_FSYNC_PIN 3U
#define CYBSP_I2S_TX_FSYNC_NUM 3U
#define CYBSP_I2S_TX_FSYNC_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define CYBSP_I2S_TX_FSYNC_INIT_DRIVESTATE 1
#ifndef ioss_0_port_12_pin_3_HSIOM
    #define ioss_0_port_12_pin_3_HSIOM HSIOM_SEL_GPIO
#endif
#define CYBSP_I2S_TX_FSYNC_HSIOM ioss_0_port_12_pin_3_HSIOM
#define CYBSP_I2S_TX_FSYNC_IRQ ioss_interrupts_gpio_12_IRQn

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
#define CYBSP_I2S_TX_FSYNC_HAL_PORT_PIN P12_3
#define CYBSP_I2S_TX_FSYNC P12_3
#define CYBSP_I2S_TX_FSYNC_HAL_IRQ CYHAL_GPIO_IRQ_NONE
#define CYBSP_I2S_TX_FSYNC_HAL_DIR CYHAL_GPIO_DIR_OUTPUT 
#define CYBSP_I2S_TX_FSYNC_HAL_DRIVEMODE CYHAL_GPIO_DRIVE_STRONG
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

#define CYBSP_WIFI_SDIO_D2_ENABLED 1U
#define CYBSP_WIFI_SDIO_D2_PORT GPIO_PRT12
#define CYBSP_WIFI_SDIO_D2_PORT_NUM 12U
#define CYBSP_WIFI_SDIO_D2_PIN 4U
#define CYBSP_WIFI_SDIO_D2_NUM 4U
#define CYBSP_WIFI_SDIO_D2_DRIVEMODE CY_GPIO_DM_STRONG
#define CYBSP_WIFI_SDIO_D2_INIT_DRIVESTATE 1
#ifndef ioss_0_port_12_pin_4_HSIOM
    #define ioss_0_port_12_pin_4_HSIOM HSIOM_SEL_GPIO
#endif
#define CYBSP_WIFI_SDIO_D2_HSIOM ioss_0_port_12_pin_4_HSIOM
#define CYBSP_WIFI_SDIO_D2_IRQ ioss_interrupts_gpio_12_IRQn

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
#define CYBSP_WIFI_SDIO_D2_HAL_PORT_PIN P12_4
#define CYBSP_WIFI_SDIO_D2 P12_4
#define CYBSP_WIFI_SDIO_D2_HAL_IRQ CYHAL_GPIO_IRQ_NONE
#define CYBSP_WIFI_SDIO_D2_HAL_DIR CYHAL_GPIO_DIR_BIDIRECTIONAL 
#define CYBSP_WIFI_SDIO_D2_HAL_DRIVEMODE CYHAL_GPIO_DRIVE_STRONG
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

#define CYBSP_WIFI_SDIO_D3_ENABLED 1U
#define CYBSP_WIFI_SDIO_D3_PORT GPIO_PRT12
#define CYBSP_WIFI_SDIO_D3_PORT_NUM 12U
#define CYBSP_WIFI_SDIO_D3_PIN 5U
#define CYBSP_WIFI_SDIO_D3_NUM 5U
#define CYBSP_WIFI_SDIO_D3_DRIVEMODE CY_GPIO_DM_STRONG
#define CYBSP_WIFI_SDIO_D3_INIT_DRIVESTATE 1
#ifndef ioss_0_port_12_pin_5_HSIOM
    #define ioss_0_port_12_pin_5_HSIOM HSIOM_SEL_GPIO
#endif
#define CYBSP_WIFI_SDIO_D3_HSIOM ioss_0_port_12_pin_5_HSIOM
#define CYBSP_WIFI_SDIO_D3_IRQ ioss_interrupts_gpio_12_IRQn

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
#define CYBSP_WIFI_SDIO_D3_HAL_PORT_PIN P12_5
#define CYBSP_WIFI_SDIO_D3 P12_5
#define CYBSP_WIFI_SDIO_D3_HAL_IRQ CYHAL_GPIO_IRQ_NONE
#define CYBSP_WIFI_SDIO_D3_HAL_DIR CYHAL_GPIO_DIR_BIDIRECTIONAL 
#define CYBSP_WIFI_SDIO_D3_HAL_DRIVEMODE CYHAL_GPIO_DRIVE_STRONG
#define CYBSP_USB_DEVICE_VBUS_DETECT (P13_0)
#define CYBSP_UART_RX3 (P13_1)
#define CYBSP_UART_TX3 (P13_2)
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

#define CYBSP_WIFI_HOST_WAKE_ENABLED 1U
#define CYBSP_WIFI_HOST_WAKE_PORT GPIO_PRT13
#define CYBSP_WIFI_HOST_WAKE_PORT_NUM 13U
#define CYBSP_WIFI_HOST_WAKE_PIN 3U
#define CYBSP_WIFI_HOST_WAKE_NUM 3U
#define CYBSP_WIFI_HOST_WAKE_DRIVEMODE CY_GPIO_DM_OD_DRIVESLOW
#define CYBSP_WIFI_HOST_WAKE_INIT_DRIVESTATE 1
#ifndef ioss_0_port_13_pin_3_HSIOM
    #define ioss_0_port_13_pin_3_HSIOM HSIOM_SEL_GPIO
#endif
#define CYBSP_WIFI_HOST_WAKE_HSIOM ioss_0_port_13_pin_3_HSIOM
#define CYBSP_WIFI_HOST_WAKE_IRQ ioss_interrupts_gpio_13_IRQn

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
#define CYBSP_WIFI_HOST_WAKE_HAL_PORT_PIN P13_3
#define CYBSP_WIFI_HOST_WAKE P13_3
#define CYBSP_WIFI_HOST_WAKE_HAL_IRQ CYHAL_GPIO_IRQ_NONE
#define CYBSP_WIFI_HOST_WAKE_HAL_DIR CYHAL_GPIO_DIR_BIDIRECTIONAL 
#define CYBSP_WIFI_HOST_WAKE_HAL_DRIVEMODE CYHAL_GPIO_DRIVE_OPENDRAINDRIVESLOW
#define CYBSP_RS_GPIO2 (P13_4)
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

#define CYBSP_SDHC_DETECT_ENABLED 1U
#define CYBSP_SDHC_DETECT_PORT GPIO_PRT13
#define CYBSP_SDHC_DETECT_PORT_NUM 13U
#define CYBSP_SDHC_DETECT_PIN 5U
#define CYBSP_SDHC_DETECT_NUM 5U
#define CYBSP_SDHC_DETECT_DRIVEMODE CY_GPIO_DM_PULLUP
#define CYBSP_SDHC_DETECT_INIT_DRIVESTATE 0
#ifndef ioss_0_port_13_pin_5_HSIOM
    #define ioss_0_port_13_pin_5_HSIOM HSIOM_SEL_GPIO
#endif
#define CYBSP_SDHC_DETECT_HSIOM ioss_0_port_13_pin_5_HSIOM
#define CYBSP_SDHC_DETECT_IRQ ioss_interrupts_gpio_13_IRQn

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
#define CYBSP_SDHC_DETECT_HAL_PORT_PIN P13_5
#define CYBSP_SDHC_DETECT P13_5
#define CYBSP_SDHC_DETECT_HAL_IRQ CYHAL_GPIO_IRQ_NONE
#define CYBSP_SDHC_DETECT_HAL_DIR CYHAL_GPIO_DIR_BIDIRECTIONAL 
#define CYBSP_SDHC_DETECT_HAL_DRIVEMODE CYHAL_GPIO_DRIVE_PULLUP
#define CYBSP_RS_GPIO1 (P13_6)
#define CYBSP_RS_RST (P13_7)
#define CYBSP_AMIC_1_INP (P14_0)
#define CYBSP_AMIC_1_INN (P14_1)
#define CYBSP_AMIC_1_OUT (P14_2)
#define CYBSP_CTB_IN_0 CYBSP_AMIC_1_OUT
#define CYBSP_AMIC_2_OUT (P14_3)
#define CYBSP_AMIC_2_INP (P14_4)
#define CYBSP_AMIC_2_INN (P14_5)
#define CYBSP_IRQ_RS (P14_6)
#define CYBSP_DVP_CAM_XCLK (P14_7)
#define CYBSP_CUR_MON_ADC1 (P15_0)
#define CYBSP_CUR_MON_ADC2 (P15_1)
#define CYBSP_MIKROBUS_AN1 (P15_2)
#define CYBSP_MIKROBUS_AN2 (P15_3)
#define CYBSP_DVP_CAM_PCLK (P15_4)
#define CYBSP_DVP_CAM_HREF (P15_5)
#define CYBSP_DVP_CAM_VSYNC (P15_6)
#define CYBSP_DVP_CAM_RST (P15_7)
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

#define CYBSP_SPI_CLK_ENABLED 1U
#define CYBSP_SPI_CLK_PORT GPIO_PRT16
#define CYBSP_SPI_CLK_PORT_NUM 16U
#define CYBSP_SPI_CLK_PIN 0U
#define CYBSP_SPI_CLK_NUM 0U
#define CYBSP_SPI_CLK_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define CYBSP_SPI_CLK_INIT_DRIVESTATE 1
#ifndef ioss_0_port_16_pin_0_HSIOM
    #define ioss_0_port_16_pin_0_HSIOM HSIOM_SEL_GPIO
#endif
#define CYBSP_SPI_CLK_HSIOM ioss_0_port_16_pin_0_HSIOM
#define CYBSP_SPI_CLK_IRQ ioss_interrupts_gpio_16_IRQn

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
#define CYBSP_SPI_CLK_HAL_PORT_PIN P16_0
#define CYBSP_SPI_CLK P16_0
#define CYBSP_SPI_CLK_HAL_IRQ CYHAL_GPIO_IRQ_NONE
#define CYBSP_SPI_CLK_HAL_DIR CYHAL_GPIO_DIR_OUTPUT 
#define CYBSP_SPI_CLK_HAL_DRIVEMODE CYHAL_GPIO_DRIVE_STRONG
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

#define CYBSP_SPI_MOSI_ENABLED 1U
#define CYBSP_SPI_MOSI_PORT GPIO_PRT16
#define CYBSP_SPI_MOSI_PORT_NUM 16U
#define CYBSP_SPI_MOSI_PIN 1U
#define CYBSP_SPI_MOSI_NUM 1U
#define CYBSP_SPI_MOSI_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define CYBSP_SPI_MOSI_INIT_DRIVESTATE 1
#ifndef ioss_0_port_16_pin_1_HSIOM
    #define ioss_0_port_16_pin_1_HSIOM HSIOM_SEL_GPIO
#endif
#define CYBSP_SPI_MOSI_HSIOM ioss_0_port_16_pin_1_HSIOM
#define CYBSP_SPI_MOSI_IRQ ioss_interrupts_gpio_16_IRQn

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
#define CYBSP_SPI_MOSI_HAL_PORT_PIN P16_1
#define CYBSP_SPI_MOSI P16_1
#define CYBSP_SPI_MOSI_HAL_IRQ CYHAL_GPIO_IRQ_NONE
#define CYBSP_SPI_MOSI_HAL_DIR CYHAL_GPIO_DIR_OUTPUT 
#define CYBSP_SPI_MOSI_HAL_DRIVEMODE CYHAL_GPIO_DRIVE_STRONG
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

#define CYBSP_SPI_MISO_ENABLED 1U
#define CYBSP_SPI_MISO_PORT GPIO_PRT16
#define CYBSP_SPI_MISO_PORT_NUM 16U
#define CYBSP_SPI_MISO_PIN 2U
#define CYBSP_SPI_MISO_NUM 2U
#define CYBSP_SPI_MISO_DRIVEMODE CY_GPIO_DM_HIGHZ
#define CYBSP_SPI_MISO_INIT_DRIVESTATE 1
#ifndef ioss_0_port_16_pin_2_HSIOM
    #define ioss_0_port_16_pin_2_HSIOM HSIOM_SEL_GPIO
#endif
#define CYBSP_SPI_MISO_HSIOM ioss_0_port_16_pin_2_HSIOM
#define CYBSP_SPI_MISO_IRQ ioss_interrupts_gpio_16_IRQn

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
#define CYBSP_SPI_MISO_HAL_PORT_PIN P16_2
#define CYBSP_SPI_MISO P16_2
#define CYBSP_SPI_MISO_HAL_IRQ CYHAL_GPIO_IRQ_NONE
#define CYBSP_SPI_MISO_HAL_DIR CYHAL_GPIO_DIR_INPUT 
#define CYBSP_SPI_MISO_HAL_DRIVEMODE CYHAL_GPIO_DRIVE_NONE
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

#define CYBSP_SPI_SS0_ENABLED 1U
#define CYBSP_SPI_SS0_PORT GPIO_PRT16
#define CYBSP_SPI_SS0_PORT_NUM 16U
#define CYBSP_SPI_SS0_PIN 3U
#define CYBSP_SPI_SS0_NUM 3U
#define CYBSP_SPI_SS0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define CYBSP_SPI_SS0_INIT_DRIVESTATE 1
#ifndef ioss_0_port_16_pin_3_HSIOM
    #define ioss_0_port_16_pin_3_HSIOM HSIOM_SEL_GPIO
#endif
#define CYBSP_SPI_SS0_HSIOM ioss_0_port_16_pin_3_HSIOM
#define CYBSP_SPI_SS0_IRQ ioss_interrupts_gpio_16_IRQn

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
#define CYBSP_SPI_SS0_HAL_PORT_PIN P16_3
#define CYBSP_SPI_SS0 P16_3
#define CYBSP_SPI_SS0_HAL_IRQ CYHAL_GPIO_IRQ_NONE
#define CYBSP_SPI_SS0_HAL_DIR CYHAL_GPIO_DIR_OUTPUT 
#define CYBSP_SPI_SS0_HAL_DRIVEMODE CYHAL_GPIO_DRIVE_STRONG
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

#define CYBSP_SPI_SS1_ENABLED 1U
#define CYBSP_SPI_SS1_PORT GPIO_PRT16
#define CYBSP_SPI_SS1_PORT_NUM 16U
#define CYBSP_SPI_SS1_PIN 4U
#define CYBSP_SPI_SS1_NUM 4U
#define CYBSP_SPI_SS1_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define CYBSP_SPI_SS1_INIT_DRIVESTATE 1
#ifndef ioss_0_port_16_pin_4_HSIOM
    #define ioss_0_port_16_pin_4_HSIOM HSIOM_SEL_GPIO
#endif
#define CYBSP_SPI_SS1_HSIOM ioss_0_port_16_pin_4_HSIOM
#define CYBSP_SPI_SS1_IRQ ioss_interrupts_gpio_16_IRQn

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
#define CYBSP_SPI_SS1_HAL_PORT_PIN P16_4
#define CYBSP_SPI_SS1 P16_4
#define CYBSP_SPI_SS1_HAL_IRQ CYHAL_GPIO_IRQ_NONE
#define CYBSP_SPI_SS1_HAL_DIR CYHAL_GPIO_DIR_OUTPUT 
#define CYBSP_SPI_SS1_HAL_DRIVEMODE CYHAL_GPIO_DRIVE_STRONG
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

#define CYBSP_DISP_BACKLIGHT_PWM_ENABLED 1U
#define CYBSP_DISP_BACKLIGHT_PWM_PORT GPIO_PRT16
#define CYBSP_DISP_BACKLIGHT_PWM_PORT_NUM 16U
#define CYBSP_DISP_BACKLIGHT_PWM_PIN 5U
#define CYBSP_DISP_BACKLIGHT_PWM_NUM 5U
#define CYBSP_DISP_BACKLIGHT_PWM_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define CYBSP_DISP_BACKLIGHT_PWM_INIT_DRIVESTATE 0
#ifndef ioss_0_port_16_pin_5_HSIOM
    #define ioss_0_port_16_pin_5_HSIOM HSIOM_SEL_GPIO
#endif
#define CYBSP_DISP_BACKLIGHT_PWM_HSIOM ioss_0_port_16_pin_5_HSIOM
#define CYBSP_DISP_BACKLIGHT_PWM_IRQ ioss_interrupts_gpio_16_IRQn

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
#define CYBSP_DISP_BACKLIGHT_PWM_HAL_PORT_PIN P16_5
#define CYBSP_DISP_BACKLIGHT_PWM P16_5
#define CYBSP_DISP_BACKLIGHT_PWM_HAL_IRQ CYHAL_GPIO_IRQ_NONE
#define CYBSP_DISP_BACKLIGHT_PWM_HAL_DIR CYHAL_GPIO_DIR_OUTPUT 
#define CYBSP_DISP_BACKLIGHT_PWM_HAL_DRIVEMODE CYHAL_GPIO_DRIVE_STRONG
#define CYBSP_DISP_RST (P16_6)
#define CYBSP_MIKROBUS_INT1 (P16_7)
#define CYBSP_UART_RX2 (P17_0)
#define CYBSP_UART_TX2 (P17_1)
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

#define CYBSP_I2C_SCL_3V3_ENABLED 1U
#define CYBSP_I2C_SCL_3V3_PORT GPIO_PRT17
#define CYBSP_I2C_SCL_3V3_PORT_NUM 17U
#define CYBSP_I2C_SCL_3V3_PIN 2U
#define CYBSP_I2C_SCL_3V3_NUM 2U
#define CYBSP_I2C_SCL_3V3_DRIVEMODE CY_GPIO_DM_OD_DRIVESLOW
#define CYBSP_I2C_SCL_3V3_INIT_DRIVESTATE 1
#ifndef ioss_0_port_17_pin_2_HSIOM
    #define ioss_0_port_17_pin_2_HSIOM HSIOM_SEL_GPIO
#endif
#define CYBSP_I2C_SCL_3V3_HSIOM ioss_0_port_17_pin_2_HSIOM
#define CYBSP_I2C_SCL_3V3_IRQ ioss_interrupts_gpio_17_IRQn

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
#define CYBSP_I2C_SCL_3V3_HAL_PORT_PIN P17_2
#define CYBSP_I2C_SCL_3V3 P17_2
#define CYBSP_I2C_SCL_3V3_HAL_IRQ CYHAL_GPIO_IRQ_NONE
#define CYBSP_I2C_SCL_3V3_HAL_DIR CYHAL_GPIO_DIR_BIDIRECTIONAL 
#define CYBSP_I2C_SCL_3V3_HAL_DRIVEMODE CYHAL_GPIO_DRIVE_OPENDRAINDRIVESLOW
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

#define CYBSP_I2C_SDA_3V3_ENABLED 1U
#define CYBSP_I2C_SDA_3V3_PORT GPIO_PRT17
#define CYBSP_I2C_SDA_3V3_PORT_NUM 17U
#define CYBSP_I2C_SDA_3V3_PIN 3U
#define CYBSP_I2C_SDA_3V3_NUM 3U
#define CYBSP_I2C_SDA_3V3_DRIVEMODE CY_GPIO_DM_OD_DRIVESLOW
#define CYBSP_I2C_SDA_3V3_INIT_DRIVESTATE 1
#ifndef ioss_0_port_17_pin_3_HSIOM
    #define ioss_0_port_17_pin_3_HSIOM HSIOM_SEL_GPIO
#endif
#define CYBSP_I2C_SDA_3V3_HSIOM ioss_0_port_17_pin_3_HSIOM
#define CYBSP_I2C_SDA_3V3_IRQ ioss_interrupts_gpio_17_IRQn

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
#define CYBSP_I2C_SDA_3V3_HAL_PORT_PIN P17_3
#define CYBSP_I2C_SDA_3V3 P17_3
#define CYBSP_I2C_SDA_3V3_HAL_IRQ CYHAL_GPIO_IRQ_NONE
#define CYBSP_I2C_SDA_3V3_HAL_DIR CYHAL_GPIO_DIR_BIDIRECTIONAL 
#define CYBSP_I2C_SDA_3V3_HAL_DRIVEMODE CYHAL_GPIO_DRIVE_OPENDRAINDRIVESLOW
#define CYBSP_MIKROBUS_RST (P17_4)
#define CYBSP_MIKROBUS_PWM1 (P17_5)
#define CYBSP_BOOT (P17_6)
#define CYBSP_MIKROBUS_PWM2 (P17_7)
#define CYBSP_WCO_OUT (P18_0)
#define CYBSP_WCO_IN (P18_1)
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

#define CYBSP_ECO_IN_ENABLED 1U
#define CYBSP_ECO_IN_PORT GPIO_PRT19
#define CYBSP_ECO_IN_PORT_NUM 19U
#define CYBSP_ECO_IN_PIN 0U
#define CYBSP_ECO_IN_NUM 0U
#define CYBSP_ECO_IN_DRIVEMODE CY_GPIO_DM_ANALOG
#define CYBSP_ECO_IN_INIT_DRIVESTATE 1
#ifndef ioss_0_port_19_pin_0_HSIOM
    #define ioss_0_port_19_pin_0_HSIOM HSIOM_SEL_GPIO
#endif
#define CYBSP_ECO_IN_HSIOM ioss_0_port_19_pin_0_HSIOM
#define CYBSP_ECO_IN_IRQ ioss_interrupts_gpio_19_IRQn

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
#define CYBSP_ECO_IN_HAL_PORT_PIN P19_0
#define CYBSP_ECO_IN P19_0
#define CYBSP_ECO_IN_HAL_IRQ CYHAL_GPIO_IRQ_NONE
#define CYBSP_ECO_IN_HAL_DIR CYHAL_GPIO_DIR_INPUT 
#define CYBSP_ECO_IN_HAL_DRIVEMODE CYHAL_GPIO_DRIVE_ANALOG
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

#define CYBSP_ECO_OUT_ENABLED 1U
#define CYBSP_ECO_OUT_PORT GPIO_PRT19
#define CYBSP_ECO_OUT_PORT_NUM 19U
#define CYBSP_ECO_OUT_PIN 1U
#define CYBSP_ECO_OUT_NUM 1U
#define CYBSP_ECO_OUT_DRIVEMODE CY_GPIO_DM_ANALOG
#define CYBSP_ECO_OUT_INIT_DRIVESTATE 1
#ifndef ioss_0_port_19_pin_1_HSIOM
    #define ioss_0_port_19_pin_1_HSIOM HSIOM_SEL_GPIO
#endif
#define CYBSP_ECO_OUT_HSIOM ioss_0_port_19_pin_1_HSIOM
#define CYBSP_ECO_OUT_IRQ ioss_interrupts_gpio_19_IRQn

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
#define CYBSP_ECO_OUT_HAL_PORT_PIN P19_1
#define CYBSP_ECO_OUT P19_1
#define CYBSP_ECO_OUT_HAL_IRQ CYHAL_GPIO_IRQ_NONE
#define CYBSP_ECO_OUT_HAL_DIR CYHAL_GPIO_DIR_INPUT 
#define CYBSP_ECO_OUT_HAL_DRIVEMODE CYHAL_GPIO_DRIVE_ANALOG
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

#define CYBSP_OSPI_D0_ENABLED 1U
#define CYBSP_QSPI_D0_ENABLED CYBSP_OSPI_D0_ENABLED
#define CYBSP_OSPI_D0_PORT (GPIO_PRT_Type*)SMIF0_CORE_SMIF_GPIO_SMIF_PRT0
#define CYBSP_QSPI_D0_PORT CYBSP_OSPI_D0_PORT
#define CYBSP_OSPI_D0_PORT_NUM 1U
#define CYBSP_QSPI_D0_PORT_NUM CYBSP_OSPI_D0_PORT_NUM
#define CYBSP_OSPI_D0_PIN 0U
#define CYBSP_QSPI_D0_PIN CYBSP_OSPI_D0_PIN
#define CYBSP_OSPI_D0_NUM 0U
#define CYBSP_QSPI_D0_NUM CYBSP_OSPI_D0_NUM
#define CYBSP_OSPI_D0_DRIVEMODE CY_GPIO_DM_STRONG
#define CYBSP_QSPI_D0_DRIVEMODE CYBSP_OSPI_D0_DRIVEMODE
#define CYBSP_OSPI_D0_INIT_DRIVESTATE 1
#define CYBSP_QSPI_D0_INIT_DRIVESTATE CYBSP_OSPI_D0_INIT_DRIVESTATE
#ifndef ioss_0_port_1_pin_0_HSIOM
    #define ioss_0_port_1_pin_0_HSIOM HSIOM_SEL_ACT_15
#endif
#define CYBSP_OSPI_D0_HSIOM ioss_0_port_1_pin_0_HSIOM
#define CYBSP_QSPI_D0_HSIOM CYBSP_OSPI_D0_HSIOM
#define CYBSP_OSPI_D0_IRQ ioss_interrupts_gpio_1_IRQn
#define CYBSP_QSPI_D0_IRQ CYBSP_OSPI_D0_IRQ

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
#define CYBSP_OSPI_D0_HAL_PORT_PIN P1_0
#define CYBSP_QSPI_D0_HAL_PORT_PIN CYBSP_OSPI_D0_HAL_PORT_PIN
#define CYBSP_OSPI_D0 P1_0
#define CYBSP_QSPI_D0 CYBSP_OSPI_D0
#define CYBSP_OSPI_D0_HAL_IRQ CYHAL_GPIO_IRQ_NONE
#define CYBSP_QSPI_D0_HAL_IRQ CYBSP_OSPI_D0_HAL_IRQ
#define CYBSP_OSPI_D0_HAL_DIR CYHAL_GPIO_DIR_BIDIRECTIONAL 
#define CYBSP_QSPI_D0_HAL_DIR CYBSP_OSPI_D0_HAL_DIR
#define CYBSP_OSPI_D0_HAL_DRIVEMODE CYHAL_GPIO_DRIVE_STRONG
#define CYBSP_QSPI_D0_HAL_DRIVEMODE CYBSP_OSPI_D0_HAL_DRIVEMODE
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

#define CYBSP_OSPI_D1_ENABLED 1U
#define CYBSP_QSPI_D1_ENABLED CYBSP_OSPI_D1_ENABLED
#define CYBSP_OSPI_D1_PORT (GPIO_PRT_Type*)SMIF0_CORE_SMIF_GPIO_SMIF_PRT0
#define CYBSP_QSPI_D1_PORT CYBSP_OSPI_D1_PORT
#define CYBSP_OSPI_D1_PORT_NUM 1U
#define CYBSP_QSPI_D1_PORT_NUM CYBSP_OSPI_D1_PORT_NUM
#define CYBSP_OSPI_D1_PIN 1U
#define CYBSP_QSPI_D1_PIN CYBSP_OSPI_D1_PIN
#define CYBSP_OSPI_D1_NUM 1U
#define CYBSP_QSPI_D1_NUM CYBSP_OSPI_D1_NUM
#define CYBSP_OSPI_D1_DRIVEMODE CY_GPIO_DM_STRONG
#define CYBSP_QSPI_D1_DRIVEMODE CYBSP_OSPI_D1_DRIVEMODE
#define CYBSP_OSPI_D1_INIT_DRIVESTATE 1
#define CYBSP_QSPI_D1_INIT_DRIVESTATE CYBSP_OSPI_D1_INIT_DRIVESTATE
#ifndef ioss_0_port_1_pin_1_HSIOM
    #define ioss_0_port_1_pin_1_HSIOM HSIOM_SEL_ACT_15
#endif
#define CYBSP_OSPI_D1_HSIOM ioss_0_port_1_pin_1_HSIOM
#define CYBSP_QSPI_D1_HSIOM CYBSP_OSPI_D1_HSIOM
#define CYBSP_OSPI_D1_IRQ ioss_interrupts_gpio_1_IRQn
#define CYBSP_QSPI_D1_IRQ CYBSP_OSPI_D1_IRQ

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
#define CYBSP_OSPI_D1_HAL_PORT_PIN P1_1
#define CYBSP_QSPI_D1_HAL_PORT_PIN CYBSP_OSPI_D1_HAL_PORT_PIN
#define CYBSP_OSPI_D1 P1_1
#define CYBSP_QSPI_D1 CYBSP_OSPI_D1
#define CYBSP_OSPI_D1_HAL_IRQ CYHAL_GPIO_IRQ_NONE
#define CYBSP_QSPI_D1_HAL_IRQ CYBSP_OSPI_D1_HAL_IRQ
#define CYBSP_OSPI_D1_HAL_DIR CYHAL_GPIO_DIR_BIDIRECTIONAL 
#define CYBSP_QSPI_D1_HAL_DIR CYBSP_OSPI_D1_HAL_DIR
#define CYBSP_OSPI_D1_HAL_DRIVEMODE CYHAL_GPIO_DRIVE_STRONG
#define CYBSP_QSPI_D1_HAL_DRIVEMODE CYBSP_OSPI_D1_HAL_DRIVEMODE
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

#define CYBSP_OSPI_D2_ENABLED 1U
#define CYBSP_QSPI_D2_ENABLED CYBSP_OSPI_D2_ENABLED
#define CYBSP_OSPI_D2_PORT (GPIO_PRT_Type*)SMIF0_CORE_SMIF_GPIO_SMIF_PRT0
#define CYBSP_QSPI_D2_PORT CYBSP_OSPI_D2_PORT
#define CYBSP_OSPI_D2_PORT_NUM 1U
#define CYBSP_QSPI_D2_PORT_NUM CYBSP_OSPI_D2_PORT_NUM
#define CYBSP_OSPI_D2_PIN 2U
#define CYBSP_QSPI_D2_PIN CYBSP_OSPI_D2_PIN
#define CYBSP_OSPI_D2_NUM 2U
#define CYBSP_QSPI_D2_NUM CYBSP_OSPI_D2_NUM
#define CYBSP_OSPI_D2_DRIVEMODE CY_GPIO_DM_STRONG
#define CYBSP_QSPI_D2_DRIVEMODE CYBSP_OSPI_D2_DRIVEMODE
#define CYBSP_OSPI_D2_INIT_DRIVESTATE 1
#define CYBSP_QSPI_D2_INIT_DRIVESTATE CYBSP_OSPI_D2_INIT_DRIVESTATE
#ifndef ioss_0_port_1_pin_2_HSIOM
    #define ioss_0_port_1_pin_2_HSIOM HSIOM_SEL_ACT_15
#endif
#define CYBSP_OSPI_D2_HSIOM ioss_0_port_1_pin_2_HSIOM
#define CYBSP_QSPI_D2_HSIOM CYBSP_OSPI_D2_HSIOM
#define CYBSP_OSPI_D2_IRQ ioss_interrupts_gpio_1_IRQn
#define CYBSP_QSPI_D2_IRQ CYBSP_OSPI_D2_IRQ

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
#define CYBSP_OSPI_D2_HAL_PORT_PIN P1_2
#define CYBSP_QSPI_D2_HAL_PORT_PIN CYBSP_OSPI_D2_HAL_PORT_PIN
#define CYBSP_OSPI_D2 P1_2
#define CYBSP_QSPI_D2 CYBSP_OSPI_D2
#define CYBSP_OSPI_D2_HAL_IRQ CYHAL_GPIO_IRQ_NONE
#define CYBSP_QSPI_D2_HAL_IRQ CYBSP_OSPI_D2_HAL_IRQ
#define CYBSP_OSPI_D2_HAL_DIR CYHAL_GPIO_DIR_BIDIRECTIONAL 
#define CYBSP_QSPI_D2_HAL_DIR CYBSP_OSPI_D2_HAL_DIR
#define CYBSP_OSPI_D2_HAL_DRIVEMODE CYHAL_GPIO_DRIVE_STRONG
#define CYBSP_QSPI_D2_HAL_DRIVEMODE CYBSP_OSPI_D2_HAL_DRIVEMODE
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

#define CYBSP_OSPI_D3_ENABLED 1U
#define CYBSP_QSPI_D3_ENABLED CYBSP_OSPI_D3_ENABLED
#define CYBSP_OSPI_D3_PORT (GPIO_PRT_Type*)SMIF0_CORE_SMIF_GPIO_SMIF_PRT0
#define CYBSP_QSPI_D3_PORT CYBSP_OSPI_D3_PORT
#define CYBSP_OSPI_D3_PORT_NUM 1U
#define CYBSP_QSPI_D3_PORT_NUM CYBSP_OSPI_D3_PORT_NUM
#define CYBSP_OSPI_D3_PIN 3U
#define CYBSP_QSPI_D3_PIN CYBSP_OSPI_D3_PIN
#define CYBSP_OSPI_D3_NUM 3U
#define CYBSP_QSPI_D3_NUM CYBSP_OSPI_D3_NUM
#define CYBSP_OSPI_D3_DRIVEMODE CY_GPIO_DM_STRONG
#define CYBSP_QSPI_D3_DRIVEMODE CYBSP_OSPI_D3_DRIVEMODE
#define CYBSP_OSPI_D3_INIT_DRIVESTATE 1
#define CYBSP_QSPI_D3_INIT_DRIVESTATE CYBSP_OSPI_D3_INIT_DRIVESTATE
#ifndef ioss_0_port_1_pin_3_HSIOM
    #define ioss_0_port_1_pin_3_HSIOM HSIOM_SEL_ACT_15
#endif
#define CYBSP_OSPI_D3_HSIOM ioss_0_port_1_pin_3_HSIOM
#define CYBSP_QSPI_D3_HSIOM CYBSP_OSPI_D3_HSIOM
#define CYBSP_OSPI_D3_IRQ ioss_interrupts_gpio_1_IRQn
#define CYBSP_QSPI_D3_IRQ CYBSP_OSPI_D3_IRQ

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
#define CYBSP_OSPI_D3_HAL_PORT_PIN P1_3
#define CYBSP_QSPI_D3_HAL_PORT_PIN CYBSP_OSPI_D3_HAL_PORT_PIN
#define CYBSP_OSPI_D3 P1_3
#define CYBSP_QSPI_D3 CYBSP_OSPI_D3
#define CYBSP_OSPI_D3_HAL_IRQ CYHAL_GPIO_IRQ_NONE
#define CYBSP_QSPI_D3_HAL_IRQ CYBSP_OSPI_D3_HAL_IRQ
#define CYBSP_OSPI_D3_HAL_DIR CYHAL_GPIO_DIR_BIDIRECTIONAL 
#define CYBSP_QSPI_D3_HAL_DIR CYBSP_OSPI_D3_HAL_DIR
#define CYBSP_OSPI_D3_HAL_DRIVEMODE CYHAL_GPIO_DRIVE_STRONG
#define CYBSP_QSPI_D3_HAL_DRIVEMODE CYBSP_OSPI_D3_HAL_DRIVEMODE
#define CYBSP_OSPI_D4 (P1_4)
#define CYBSP_OSPI_D5 (P1_5)
#define CYBSP_OSPI_D6 (P1_6)
#define CYBSP_OSPI_D7 (P1_7)
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

#define CYBSP_USER_LED1_ENABLED 1U
#define CYBSP_USER_LED_ENABLED CYBSP_USER_LED1_ENABLED
#define CYBSP_LED_RGB_RED_ENABLED CYBSP_USER_LED1_ENABLED
#define CYBSP_LED_RED_ENABLED CYBSP_USER_LED1_ENABLED
#define CYBSP_USER_LED1_PORT GPIO_PRT20
#define CYBSP_USER_LED_PORT CYBSP_USER_LED1_PORT
#define CYBSP_LED_RGB_RED_PORT CYBSP_USER_LED1_PORT
#define CYBSP_LED_RED_PORT CYBSP_USER_LED1_PORT
#define CYBSP_USER_LED1_PORT_NUM 20U
#define CYBSP_USER_LED_PORT_NUM CYBSP_USER_LED1_PORT_NUM
#define CYBSP_LED_RGB_RED_PORT_NUM CYBSP_USER_LED1_PORT_NUM
#define CYBSP_LED_RED_PORT_NUM CYBSP_USER_LED1_PORT_NUM
#define CYBSP_USER_LED1_PIN 0U
#define CYBSP_USER_LED_PIN CYBSP_USER_LED1_PIN
#define CYBSP_LED_RGB_RED_PIN CYBSP_USER_LED1_PIN
#define CYBSP_LED_RED_PIN CYBSP_USER_LED1_PIN
#define CYBSP_USER_LED1_NUM 0U
#define CYBSP_USER_LED_NUM CYBSP_USER_LED1_NUM
#define CYBSP_LED_RGB_RED_NUM CYBSP_USER_LED1_NUM
#define CYBSP_LED_RED_NUM CYBSP_USER_LED1_NUM
#define CYBSP_USER_LED1_DRIVEMODE CY_GPIO_DM_PULLUP
#define CYBSP_USER_LED_DRIVEMODE CYBSP_USER_LED1_DRIVEMODE
#define CYBSP_LED_RGB_RED_DRIVEMODE CYBSP_USER_LED1_DRIVEMODE
#define CYBSP_LED_RED_DRIVEMODE CYBSP_USER_LED1_DRIVEMODE
#define CYBSP_USER_LED1_INIT_DRIVESTATE 0
#define CYBSP_USER_LED_INIT_DRIVESTATE CYBSP_USER_LED1_INIT_DRIVESTATE
#define CYBSP_LED_RGB_RED_INIT_DRIVESTATE CYBSP_USER_LED1_INIT_DRIVESTATE
#define CYBSP_LED_RED_INIT_DRIVESTATE CYBSP_USER_LED1_INIT_DRIVESTATE
#ifndef ioss_0_port_20_pin_0_HSIOM
    #define ioss_0_port_20_pin_0_HSIOM HSIOM_SEL_GPIO
#endif
#define CYBSP_USER_LED1_HSIOM ioss_0_port_20_pin_0_HSIOM
#define CYBSP_USER_LED_HSIOM CYBSP_USER_LED1_HSIOM
#define CYBSP_LED_RGB_RED_HSIOM CYBSP_USER_LED1_HSIOM
#define CYBSP_LED_RED_HSIOM CYBSP_USER_LED1_HSIOM
#define CYBSP_USER_LED1_IRQ ioss_interrupts_gpio_20_IRQn
#define CYBSP_USER_LED_IRQ CYBSP_USER_LED1_IRQ
#define CYBSP_LED_RGB_RED_IRQ CYBSP_USER_LED1_IRQ
#define CYBSP_LED_RED_IRQ CYBSP_USER_LED1_IRQ

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
#define CYBSP_USER_LED1_HAL_PORT_PIN P20_0
#define CYBSP_USER_LED_HAL_PORT_PIN CYBSP_USER_LED1_HAL_PORT_PIN
#define CYBSP_LED_RGB_RED_HAL_PORT_PIN CYBSP_USER_LED1_HAL_PORT_PIN
#define CYBSP_LED_RED_HAL_PORT_PIN CYBSP_USER_LED1_HAL_PORT_PIN
#define CYBSP_USER_LED1 P20_0
#define CYBSP_USER_LED CYBSP_USER_LED1
#define CYBSP_LED_RGB_RED CYBSP_USER_LED1
#define CYBSP_LED_RED CYBSP_USER_LED1
#define CYBSP_USER_LED1_HAL_IRQ CYHAL_GPIO_IRQ_NONE
#define CYBSP_USER_LED_HAL_IRQ CYBSP_USER_LED1_HAL_IRQ
#define CYBSP_LED_RGB_RED_HAL_IRQ CYBSP_USER_LED1_HAL_IRQ
#define CYBSP_LED_RED_HAL_IRQ CYBSP_USER_LED1_HAL_IRQ
#define CYBSP_USER_LED1_HAL_DIR CYHAL_GPIO_DIR_BIDIRECTIONAL 
#define CYBSP_USER_LED_HAL_DIR CYBSP_USER_LED1_HAL_DIR
#define CYBSP_LED_RGB_RED_HAL_DIR CYBSP_USER_LED1_HAL_DIR
#define CYBSP_LED_RED_HAL_DIR CYBSP_USER_LED1_HAL_DIR
#define CYBSP_USER_LED1_HAL_DRIVEMODE CYHAL_GPIO_DRIVE_PULLUP
#define CYBSP_USER_LED_HAL_DRIVEMODE CYBSP_USER_LED1_HAL_DRIVEMODE
#define CYBSP_LED_RGB_RED_HAL_DRIVEMODE CYBSP_USER_LED1_HAL_DRIVEMODE
#define CYBSP_LED_RED_HAL_DRIVEMODE CYBSP_USER_LED1_HAL_DRIVEMODE
#define CYBSP_ALT_SER_INT_CONFIG_2 (P20_1)
#define CYBSP_ALT_SER_INT_CONFIG_1 (P20_2)
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

#define CYBSP_USER_LED2_ENABLED 1U
#define CYBSP_USER_LED_RGB_GREEN_ENABLED CYBSP_USER_LED2_ENABLED
#define CYBSP_LED_GREEN_ENABLED CYBSP_USER_LED2_ENABLED
#define CYBSP_USER_LED2_PORT GPIO_PRT20
#define CYBSP_USER_LED_RGB_GREEN_PORT CYBSP_USER_LED2_PORT
#define CYBSP_LED_GREEN_PORT CYBSP_USER_LED2_PORT
#define CYBSP_USER_LED2_PORT_NUM 20U
#define CYBSP_USER_LED_RGB_GREEN_PORT_NUM CYBSP_USER_LED2_PORT_NUM
#define CYBSP_LED_GREEN_PORT_NUM CYBSP_USER_LED2_PORT_NUM
#define CYBSP_USER_LED2_PIN 3U
#define CYBSP_USER_LED_RGB_GREEN_PIN CYBSP_USER_LED2_PIN
#define CYBSP_LED_GREEN_PIN CYBSP_USER_LED2_PIN
#define CYBSP_USER_LED2_NUM 3U
#define CYBSP_USER_LED_RGB_GREEN_NUM CYBSP_USER_LED2_NUM
#define CYBSP_LED_GREEN_NUM CYBSP_USER_LED2_NUM
#define CYBSP_USER_LED2_DRIVEMODE CY_GPIO_DM_STRONG
#define CYBSP_USER_LED_RGB_GREEN_DRIVEMODE CYBSP_USER_LED2_DRIVEMODE
#define CYBSP_LED_GREEN_DRIVEMODE CYBSP_USER_LED2_DRIVEMODE
#define CYBSP_USER_LED2_INIT_DRIVESTATE 0
#define CYBSP_USER_LED_RGB_GREEN_INIT_DRIVESTATE CYBSP_USER_LED2_INIT_DRIVESTATE
#define CYBSP_LED_GREEN_INIT_DRIVESTATE CYBSP_USER_LED2_INIT_DRIVESTATE
#ifndef ioss_0_port_20_pin_3_HSIOM
    #define ioss_0_port_20_pin_3_HSIOM HSIOM_SEL_GPIO
#endif
#define CYBSP_USER_LED2_HSIOM ioss_0_port_20_pin_3_HSIOM
#define CYBSP_USER_LED_RGB_GREEN_HSIOM CYBSP_USER_LED2_HSIOM
#define CYBSP_LED_GREEN_HSIOM CYBSP_USER_LED2_HSIOM
#define CYBSP_USER_LED2_IRQ ioss_interrupts_gpio_20_IRQn
#define CYBSP_USER_LED_RGB_GREEN_IRQ CYBSP_USER_LED2_IRQ
#define CYBSP_LED_GREEN_IRQ CYBSP_USER_LED2_IRQ

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
#define CYBSP_USER_LED2_HAL_PORT_PIN P20_3
#define CYBSP_USER_LED_RGB_GREEN_HAL_PORT_PIN CYBSP_USER_LED2_HAL_PORT_PIN
#define CYBSP_LED_GREEN_HAL_PORT_PIN CYBSP_USER_LED2_HAL_PORT_PIN
#define CYBSP_USER_LED2 P20_3
#define CYBSP_USER_LED_RGB_GREEN CYBSP_USER_LED2
#define CYBSP_LED_GREEN CYBSP_USER_LED2
#define CYBSP_USER_LED2_HAL_IRQ CYHAL_GPIO_IRQ_NONE
#define CYBSP_USER_LED_RGB_GREEN_HAL_IRQ CYBSP_USER_LED2_HAL_IRQ
#define CYBSP_LED_GREEN_HAL_IRQ CYBSP_USER_LED2_HAL_IRQ
#define CYBSP_USER_LED2_HAL_DIR CYHAL_GPIO_DIR_BIDIRECTIONAL 
#define CYBSP_USER_LED_RGB_GREEN_HAL_DIR CYBSP_USER_LED2_HAL_DIR
#define CYBSP_LED_GREEN_HAL_DIR CYBSP_USER_LED2_HAL_DIR
#define CYBSP_USER_LED2_HAL_DRIVEMODE CYHAL_GPIO_DRIVE_STRONG
#define CYBSP_USER_LED_RGB_GREEN_HAL_DRIVEMODE CYBSP_USER_LED2_HAL_DRIVEMODE
#define CYBSP_LED_GREEN_HAL_DRIVEMODE CYBSP_USER_LED2_HAL_DRIVEMODE
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

#define CYBSP_USER_LED3_ENABLED 1U
#define CYBSP_USER_LED_RGB_BLUE_ENABLED CYBSP_USER_LED3_ENABLED
#define CYBSP_LED_BLUE_ENABLED CYBSP_USER_LED3_ENABLED
#define CYBSP_USER_LED3_PORT GPIO_PRT20
#define CYBSP_USER_LED_RGB_BLUE_PORT CYBSP_USER_LED3_PORT
#define CYBSP_LED_BLUE_PORT CYBSP_USER_LED3_PORT
#define CYBSP_USER_LED3_PORT_NUM 20U
#define CYBSP_USER_LED_RGB_BLUE_PORT_NUM CYBSP_USER_LED3_PORT_NUM
#define CYBSP_LED_BLUE_PORT_NUM CYBSP_USER_LED3_PORT_NUM
#define CYBSP_USER_LED3_PIN 4U
#define CYBSP_USER_LED_RGB_BLUE_PIN CYBSP_USER_LED3_PIN
#define CYBSP_LED_BLUE_PIN CYBSP_USER_LED3_PIN
#define CYBSP_USER_LED3_NUM 4U
#define CYBSP_USER_LED_RGB_BLUE_NUM CYBSP_USER_LED3_NUM
#define CYBSP_LED_BLUE_NUM CYBSP_USER_LED3_NUM
#define CYBSP_USER_LED3_DRIVEMODE CY_GPIO_DM_STRONG
#define CYBSP_USER_LED_RGB_BLUE_DRIVEMODE CYBSP_USER_LED3_DRIVEMODE
#define CYBSP_LED_BLUE_DRIVEMODE CYBSP_USER_LED3_DRIVEMODE
#define CYBSP_USER_LED3_INIT_DRIVESTATE 0
#define CYBSP_USER_LED_RGB_BLUE_INIT_DRIVESTATE CYBSP_USER_LED3_INIT_DRIVESTATE
#define CYBSP_LED_BLUE_INIT_DRIVESTATE CYBSP_USER_LED3_INIT_DRIVESTATE
#ifndef ioss_0_port_20_pin_4_HSIOM
    #define ioss_0_port_20_pin_4_HSIOM HSIOM_SEL_GPIO
#endif
#define CYBSP_USER_LED3_HSIOM ioss_0_port_20_pin_4_HSIOM
#define CYBSP_USER_LED_RGB_BLUE_HSIOM CYBSP_USER_LED3_HSIOM
#define CYBSP_LED_BLUE_HSIOM CYBSP_USER_LED3_HSIOM
#define CYBSP_USER_LED3_IRQ ioss_interrupts_gpio_20_IRQn
#define CYBSP_USER_LED_RGB_BLUE_IRQ CYBSP_USER_LED3_IRQ
#define CYBSP_LED_BLUE_IRQ CYBSP_USER_LED3_IRQ

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
#define CYBSP_USER_LED3_HAL_PORT_PIN P20_4
#define CYBSP_USER_LED_RGB_BLUE_HAL_PORT_PIN CYBSP_USER_LED3_HAL_PORT_PIN
#define CYBSP_LED_BLUE_HAL_PORT_PIN CYBSP_USER_LED3_HAL_PORT_PIN
#define CYBSP_USER_LED3 P20_4
#define CYBSP_USER_LED_RGB_BLUE CYBSP_USER_LED3
#define CYBSP_LED_BLUE CYBSP_USER_LED3
#define CYBSP_USER_LED3_HAL_IRQ CYHAL_GPIO_IRQ_NONE
#define CYBSP_USER_LED_RGB_BLUE_HAL_IRQ CYBSP_USER_LED3_HAL_IRQ
#define CYBSP_LED_BLUE_HAL_IRQ CYBSP_USER_LED3_HAL_IRQ
#define CYBSP_USER_LED3_HAL_DIR CYHAL_GPIO_DIR_BIDIRECTIONAL 
#define CYBSP_USER_LED_RGB_BLUE_HAL_DIR CYBSP_USER_LED3_HAL_DIR
#define CYBSP_LED_BLUE_HAL_DIR CYBSP_USER_LED3_HAL_DIR
#define CYBSP_USER_LED3_HAL_DRIVEMODE CYHAL_GPIO_DRIVE_STRONG
#define CYBSP_USER_LED_RGB_BLUE_HAL_DRIVEMODE CYBSP_USER_LED3_HAL_DRIVEMODE
#define CYBSP_LED_BLUE_HAL_DRIVEMODE CYBSP_USER_LED3_HAL_DRIVEMODE
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

#define CYBSP_STATUS_LED1_ENABLED 1U
#define CYBSP_STATUS_LED1_PORT GPIO_PRT20
#define CYBSP_STATUS_LED1_PORT_NUM 20U
#define CYBSP_STATUS_LED1_PIN 5U
#define CYBSP_STATUS_LED1_NUM 5U
#define CYBSP_STATUS_LED1_DRIVEMODE CY_GPIO_DM_STRONG
#define CYBSP_STATUS_LED1_INIT_DRIVESTATE 0
#ifndef ioss_0_port_20_pin_5_HSIOM
    #define ioss_0_port_20_pin_5_HSIOM HSIOM_SEL_GPIO
#endif
#define CYBSP_STATUS_LED1_HSIOM ioss_0_port_20_pin_5_HSIOM
#define CYBSP_STATUS_LED1_IRQ ioss_interrupts_gpio_20_IRQn

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
#define CYBSP_STATUS_LED1_HAL_PORT_PIN P20_5
#define CYBSP_STATUS_LED1 P20_5
#define CYBSP_STATUS_LED1_HAL_IRQ CYHAL_GPIO_IRQ_NONE
#define CYBSP_STATUS_LED1_HAL_DIR CYHAL_GPIO_DIR_BIDIRECTIONAL 
#define CYBSP_STATUS_LED1_HAL_DRIVEMODE CYHAL_GPIO_DRIVE_STRONG
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

#define CYBSP_STATUS_LED2_ENABLED 1U
#define CYBSP_STATUS_LED2_PORT GPIO_PRT20
#define CYBSP_STATUS_LED2_PORT_NUM 20U
#define CYBSP_STATUS_LED2_PIN 6U
#define CYBSP_STATUS_LED2_NUM 6U
#define CYBSP_STATUS_LED2_DRIVEMODE CY_GPIO_DM_STRONG
#define CYBSP_STATUS_LED2_INIT_DRIVESTATE 0
#ifndef ioss_0_port_20_pin_6_HSIOM
    #define ioss_0_port_20_pin_6_HSIOM HSIOM_SEL_GPIO
#endif
#define CYBSP_STATUS_LED2_HSIOM ioss_0_port_20_pin_6_HSIOM
#define CYBSP_STATUS_LED2_IRQ ioss_interrupts_gpio_20_IRQn

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
#define CYBSP_STATUS_LED2_HAL_PORT_PIN P20_6
#define CYBSP_STATUS_LED2 P20_6
#define CYBSP_STATUS_LED2_HAL_IRQ CYHAL_GPIO_IRQ_NONE
#define CYBSP_STATUS_LED2_HAL_DIR CYHAL_GPIO_DIR_BIDIRECTIONAL 
#define CYBSP_STATUS_LED2_HAL_DRIVEMODE CYHAL_GPIO_DRIVE_STRONG
#define CYBSP_DVP_CAM_PWDN (P20_7)
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

#define CYBSP_WIFI_SDIO_CMD_ENABLED 1U
#define CYBSP_WIFI_SDIO_CMD_PORT GPIO_PRT21
#define CYBSP_WIFI_SDIO_CMD_PORT_NUM 21U
#define CYBSP_WIFI_SDIO_CMD_PIN 0U
#define CYBSP_WIFI_SDIO_CMD_NUM 0U
#define CYBSP_WIFI_SDIO_CMD_DRIVEMODE CY_GPIO_DM_STRONG
#define CYBSP_WIFI_SDIO_CMD_INIT_DRIVESTATE 1
#ifndef ioss_0_port_21_pin_0_HSIOM
    #define ioss_0_port_21_pin_0_HSIOM HSIOM_SEL_GPIO
#endif
#define CYBSP_WIFI_SDIO_CMD_HSIOM ioss_0_port_21_pin_0_HSIOM
#define CYBSP_WIFI_SDIO_CMD_IRQ ioss_interrupts_gpio_21_IRQn

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
#define CYBSP_WIFI_SDIO_CMD_HAL_PORT_PIN P21_0
#define CYBSP_WIFI_SDIO_CMD P21_0
#define CYBSP_WIFI_SDIO_CMD_HAL_IRQ CYHAL_GPIO_IRQ_NONE
#define CYBSP_WIFI_SDIO_CMD_HAL_DIR CYHAL_GPIO_DIR_BIDIRECTIONAL 
#define CYBSP_WIFI_SDIO_CMD_HAL_DRIVEMODE CYHAL_GPIO_DRIVE_STRONG
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

#define CYBSP_I2S_TX_SD_ENABLED 1U
#define CYBSP_I2S_TX_SD_PORT GPIO_PRT21
#define CYBSP_I2S_TX_SD_PORT_NUM 21U
#define CYBSP_I2S_TX_SD_PIN 1U
#define CYBSP_I2S_TX_SD_NUM 1U
#define CYBSP_I2S_TX_SD_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define CYBSP_I2S_TX_SD_INIT_DRIVESTATE 1
#ifndef ioss_0_port_21_pin_1_HSIOM
    #define ioss_0_port_21_pin_1_HSIOM HSIOM_SEL_GPIO
#endif
#define CYBSP_I2S_TX_SD_HSIOM ioss_0_port_21_pin_1_HSIOM
#define CYBSP_I2S_TX_SD_IRQ ioss_interrupts_gpio_21_IRQn

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
#define CYBSP_I2S_TX_SD_HAL_PORT_PIN P21_1
#define CYBSP_I2S_TX_SD P21_1
#define CYBSP_I2S_TX_SD_HAL_IRQ CYHAL_GPIO_IRQ_NONE
#define CYBSP_I2S_TX_SD_HAL_DIR CYHAL_GPIO_DIR_OUTPUT 
#define CYBSP_I2S_TX_SD_HAL_DRIVEMODE CYHAL_GPIO_DRIVE_STRONG
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

#define CYBSP_I2S_TX_SCK_ENABLED 1U
#define CYBSP_I2S_TX_SCK_PORT GPIO_PRT21
#define CYBSP_I2S_TX_SCK_PORT_NUM 21U
#define CYBSP_I2S_TX_SCK_PIN 2U
#define CYBSP_I2S_TX_SCK_NUM 2U
#define CYBSP_I2S_TX_SCK_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define CYBSP_I2S_TX_SCK_INIT_DRIVESTATE 1
#ifndef ioss_0_port_21_pin_2_HSIOM
    #define ioss_0_port_21_pin_2_HSIOM HSIOM_SEL_GPIO
#endif
#define CYBSP_I2S_TX_SCK_HSIOM ioss_0_port_21_pin_2_HSIOM
#define CYBSP_I2S_TX_SCK_IRQ ioss_interrupts_gpio_21_IRQn

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
#define CYBSP_I2S_TX_SCK_HAL_PORT_PIN P21_2
#define CYBSP_I2S_TX_SCK P21_2
#define CYBSP_I2S_TX_SCK_HAL_IRQ CYHAL_GPIO_IRQ_NONE
#define CYBSP_I2S_TX_SCK_HAL_DIR CYHAL_GPIO_DIR_OUTPUT 
#define CYBSP_I2S_TX_SCK_HAL_DRIVEMODE CYHAL_GPIO_DRIVE_STRONG
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

#define CYBSP_I2S_TX_MCK_ENABLED 1U
#define CYBSP_I2S_TX_MCK_PORT GPIO_PRT21
#define CYBSP_I2S_TX_MCK_PORT_NUM 21U
#define CYBSP_I2S_TX_MCK_PIN 3U
#define CYBSP_I2S_TX_MCK_NUM 3U
#define CYBSP_I2S_TX_MCK_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define CYBSP_I2S_TX_MCK_INIT_DRIVESTATE 1
#ifndef ioss_0_port_21_pin_3_HSIOM
    #define ioss_0_port_21_pin_3_HSIOM HSIOM_SEL_GPIO
#endif
#define CYBSP_I2S_TX_MCK_HSIOM ioss_0_port_21_pin_3_HSIOM
#define CYBSP_I2S_TX_MCK_IRQ ioss_interrupts_gpio_21_IRQn

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
#define CYBSP_I2S_TX_MCK_HAL_PORT_PIN P21_3
#define CYBSP_I2S_TX_MCK P21_3
#define CYBSP_I2S_TX_MCK_HAL_IRQ CYHAL_GPIO_IRQ_NONE
#define CYBSP_I2S_TX_MCK_HAL_DIR CYHAL_GPIO_DIR_OUTPUT 
#define CYBSP_I2S_TX_MCK_HAL_DRIVEMODE CYHAL_GPIO_DRIVE_STRONG
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

#define CYBSP_RS_SPI_MISO_ENABLED 1U
#define CYBSP_RS_SPI_MISO_PORT GPIO_PRT21
#define CYBSP_RS_SPI_MISO_PORT_NUM 21U
#define CYBSP_RS_SPI_MISO_PIN 4U
#define CYBSP_RS_SPI_MISO_NUM 4U
#define CYBSP_RS_SPI_MISO_DRIVEMODE CY_GPIO_DM_HIGHZ
#define CYBSP_RS_SPI_MISO_INIT_DRIVESTATE 1
#ifndef ioss_0_port_21_pin_4_HSIOM
    #define ioss_0_port_21_pin_4_HSIOM HSIOM_SEL_GPIO
#endif
#define CYBSP_RS_SPI_MISO_HSIOM ioss_0_port_21_pin_4_HSIOM
#define CYBSP_RS_SPI_MISO_IRQ ioss_interrupts_gpio_21_IRQn

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
#define CYBSP_RS_SPI_MISO_HAL_PORT_PIN P21_4
#define CYBSP_RS_SPI_MISO P21_4
#define CYBSP_RS_SPI_MISO_HAL_IRQ CYHAL_GPIO_IRQ_NONE
#define CYBSP_RS_SPI_MISO_HAL_DIR CYHAL_GPIO_DIR_INPUT 
#define CYBSP_RS_SPI_MISO_HAL_DRIVEMODE CYHAL_GPIO_DRIVE_NONE
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

#define CYBSP_RS_SPI_MOSI_ENABLED 1U
#define CYBSP_RS_SPI_MOSI_PORT GPIO_PRT21
#define CYBSP_RS_SPI_MOSI_PORT_NUM 21U
#define CYBSP_RS_SPI_MOSI_PIN 5U
#define CYBSP_RS_SPI_MOSI_NUM 5U
#define CYBSP_RS_SPI_MOSI_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define CYBSP_RS_SPI_MOSI_INIT_DRIVESTATE 1
#ifndef ioss_0_port_21_pin_5_HSIOM
    #define ioss_0_port_21_pin_5_HSIOM HSIOM_SEL_GPIO
#endif
#define CYBSP_RS_SPI_MOSI_HSIOM ioss_0_port_21_pin_5_HSIOM
#define CYBSP_RS_SPI_MOSI_IRQ ioss_interrupts_gpio_21_IRQn

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
#define CYBSP_RS_SPI_MOSI_HAL_PORT_PIN P21_5
#define CYBSP_RS_SPI_MOSI P21_5
#define CYBSP_RS_SPI_MOSI_HAL_IRQ CYHAL_GPIO_IRQ_NONE
#define CYBSP_RS_SPI_MOSI_HAL_DIR CYHAL_GPIO_DIR_OUTPUT 
#define CYBSP_RS_SPI_MOSI_HAL_DRIVEMODE CYHAL_GPIO_DRIVE_STRONG
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

#define CYBSP_RS_SPI_CLK_ENABLED 1U
#define CYBSP_RS_SPI_CLK_PORT GPIO_PRT21
#define CYBSP_RS_SPI_CLK_PORT_NUM 21U
#define CYBSP_RS_SPI_CLK_PIN 6U
#define CYBSP_RS_SPI_CLK_NUM 6U
#define CYBSP_RS_SPI_CLK_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define CYBSP_RS_SPI_CLK_INIT_DRIVESTATE 1
#ifndef ioss_0_port_21_pin_6_HSIOM
    #define ioss_0_port_21_pin_6_HSIOM HSIOM_SEL_GPIO
#endif
#define CYBSP_RS_SPI_CLK_HSIOM ioss_0_port_21_pin_6_HSIOM
#define CYBSP_RS_SPI_CLK_IRQ ioss_interrupts_gpio_21_IRQn

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
#define CYBSP_RS_SPI_CLK_HAL_PORT_PIN P21_6
#define CYBSP_RS_SPI_CLK P21_6
#define CYBSP_RS_SPI_CLK_HAL_IRQ CYHAL_GPIO_IRQ_NONE
#define CYBSP_RS_SPI_CLK_HAL_DIR CYHAL_GPIO_DIR_OUTPUT 
#define CYBSP_RS_SPI_CLK_HAL_DRIVEMODE CYHAL_GPIO_DRIVE_STRONG
#define CYBSP_CO2_5V_EN (P21_7)
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

#define CYBSP_QSPI_SS_ENABLED 1U
#define CYBSP_QSPI_SS_PORT GPIO_PRT2
#define CYBSP_QSPI_SS_PORT_NUM 2U
#define CYBSP_QSPI_SS_PIN 0U
#define CYBSP_QSPI_SS_NUM 0U
#define CYBSP_QSPI_SS_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define CYBSP_QSPI_SS_INIT_DRIVESTATE 1
#ifndef ioss_0_port_2_pin_0_HSIOM
    #define ioss_0_port_2_pin_0_HSIOM HSIOM_SEL_GPIO
#endif
#define CYBSP_QSPI_SS_HSIOM ioss_0_port_2_pin_0_HSIOM
#define CYBSP_QSPI_SS_IRQ ioss_interrupts_gpio_2_IRQn

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
#define CYBSP_QSPI_SS_HAL_PORT_PIN P2_0
#define CYBSP_QSPI_SS P2_0
#define CYBSP_QSPI_SS_HAL_IRQ CYHAL_GPIO_IRQ_NONE
#define CYBSP_QSPI_SS_HAL_DIR CYHAL_GPIO_DIR_OUTPUT 
#define CYBSP_QSPI_SS_HAL_DRIVEMODE CYHAL_GPIO_DRIVE_STRONG
#define CYBSP_MEMORY_RST (P3_0)
#define CYBSP_MIKROBUS_INT2 (P3_1)
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

#define CYBSP_OSPI_RAM_D0_ENABLED 1U
#define CYBSP_OSPI_RAM_D0_PORT (GPIO_PRT_Type*)SMIF1_CORE_SMIF_GPIO_SMIF_PRT0
#define CYBSP_OSPI_RAM_D0_PORT_NUM 4U
#define CYBSP_OSPI_RAM_D0_PIN 0U
#define CYBSP_OSPI_RAM_D0_NUM 0U
#define CYBSP_OSPI_RAM_D0_DRIVEMODE CY_GPIO_DM_STRONG
#define CYBSP_OSPI_RAM_D0_INIT_DRIVESTATE 1
#ifndef ioss_0_port_4_pin_0_HSIOM
    #define ioss_0_port_4_pin_0_HSIOM HSIOM_SEL_ACT_15
#endif
#define CYBSP_OSPI_RAM_D0_HSIOM ioss_0_port_4_pin_0_HSIOM
#define CYBSP_OSPI_RAM_D0_IRQ ioss_interrupts_gpio_4_IRQn

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
#define CYBSP_OSPI_RAM_D0_HAL_PORT_PIN P4_0
#define CYBSP_OSPI_RAM_D0 P4_0
#define CYBSP_OSPI_RAM_D0_HAL_IRQ CYHAL_GPIO_IRQ_NONE
#define CYBSP_OSPI_RAM_D0_HAL_DIR CYHAL_GPIO_DIR_BIDIRECTIONAL 
#define CYBSP_OSPI_RAM_D0_HAL_DRIVEMODE CYHAL_GPIO_DRIVE_STRONG
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

#define CYBSP_OSPI_RAM_D1_ENABLED 1U
#define CYBSP_OSPI_RAM_D1_PORT (GPIO_PRT_Type*)SMIF1_CORE_SMIF_GPIO_SMIF_PRT0
#define CYBSP_OSPI_RAM_D1_PORT_NUM 4U
#define CYBSP_OSPI_RAM_D1_PIN 1U
#define CYBSP_OSPI_RAM_D1_NUM 1U
#define CYBSP_OSPI_RAM_D1_DRIVEMODE CY_GPIO_DM_STRONG
#define CYBSP_OSPI_RAM_D1_INIT_DRIVESTATE 1
#ifndef ioss_0_port_4_pin_1_HSIOM
    #define ioss_0_port_4_pin_1_HSIOM HSIOM_SEL_ACT_15
#endif
#define CYBSP_OSPI_RAM_D1_HSIOM ioss_0_port_4_pin_1_HSIOM
#define CYBSP_OSPI_RAM_D1_IRQ ioss_interrupts_gpio_4_IRQn

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
#define CYBSP_OSPI_RAM_D1_HAL_PORT_PIN P4_1
#define CYBSP_OSPI_RAM_D1 P4_1
#define CYBSP_OSPI_RAM_D1_HAL_IRQ CYHAL_GPIO_IRQ_NONE
#define CYBSP_OSPI_RAM_D1_HAL_DIR CYHAL_GPIO_DIR_BIDIRECTIONAL 
#define CYBSP_OSPI_RAM_D1_HAL_DRIVEMODE CYHAL_GPIO_DRIVE_STRONG
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

#define CYBSP_OSPI_RAM_D2_ENABLED 1U
#define CYBSP_OSPI_RAM_D2_PORT (GPIO_PRT_Type*)SMIF1_CORE_SMIF_GPIO_SMIF_PRT0
#define CYBSP_OSPI_RAM_D2_PORT_NUM 4U
#define CYBSP_OSPI_RAM_D2_PIN 2U
#define CYBSP_OSPI_RAM_D2_NUM 2U
#define CYBSP_OSPI_RAM_D2_DRIVEMODE CY_GPIO_DM_STRONG
#define CYBSP_OSPI_RAM_D2_INIT_DRIVESTATE 1
#ifndef ioss_0_port_4_pin_2_HSIOM
    #define ioss_0_port_4_pin_2_HSIOM HSIOM_SEL_ACT_15
#endif
#define CYBSP_OSPI_RAM_D2_HSIOM ioss_0_port_4_pin_2_HSIOM
#define CYBSP_OSPI_RAM_D2_IRQ ioss_interrupts_gpio_4_IRQn

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
#define CYBSP_OSPI_RAM_D2_HAL_PORT_PIN P4_2
#define CYBSP_OSPI_RAM_D2 P4_2
#define CYBSP_OSPI_RAM_D2_HAL_IRQ CYHAL_GPIO_IRQ_NONE
#define CYBSP_OSPI_RAM_D2_HAL_DIR CYHAL_GPIO_DIR_BIDIRECTIONAL 
#define CYBSP_OSPI_RAM_D2_HAL_DRIVEMODE CYHAL_GPIO_DRIVE_STRONG
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

#define CYBSP_OSPI_RAM_D3_ENABLED 1U
#define CYBSP_OSPI_RAM_D3_PORT (GPIO_PRT_Type*)SMIF1_CORE_SMIF_GPIO_SMIF_PRT0
#define CYBSP_OSPI_RAM_D3_PORT_NUM 4U
#define CYBSP_OSPI_RAM_D3_PIN 3U
#define CYBSP_OSPI_RAM_D3_NUM 3U
#define CYBSP_OSPI_RAM_D3_DRIVEMODE CY_GPIO_DM_STRONG
#define CYBSP_OSPI_RAM_D3_INIT_DRIVESTATE 1
#ifndef ioss_0_port_4_pin_3_HSIOM
    #define ioss_0_port_4_pin_3_HSIOM HSIOM_SEL_ACT_15
#endif
#define CYBSP_OSPI_RAM_D3_HSIOM ioss_0_port_4_pin_3_HSIOM
#define CYBSP_OSPI_RAM_D3_IRQ ioss_interrupts_gpio_4_IRQn

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
#define CYBSP_OSPI_RAM_D3_HAL_PORT_PIN P4_3
#define CYBSP_OSPI_RAM_D3 P4_3
#define CYBSP_OSPI_RAM_D3_HAL_IRQ CYHAL_GPIO_IRQ_NONE
#define CYBSP_OSPI_RAM_D3_HAL_DIR CYHAL_GPIO_DIR_BIDIRECTIONAL 
#define CYBSP_OSPI_RAM_D3_HAL_DRIVEMODE CYHAL_GPIO_DRIVE_STRONG
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

#define CYBSP_OSPI_RAM_D4_ENABLED 1U
#define CYBSP_OSPI_RAM_D4_PORT (GPIO_PRT_Type*)SMIF1_CORE_SMIF_GPIO_SMIF_PRT0
#define CYBSP_OSPI_RAM_D4_PORT_NUM 4U
#define CYBSP_OSPI_RAM_D4_PIN 4U
#define CYBSP_OSPI_RAM_D4_NUM 4U
#define CYBSP_OSPI_RAM_D4_DRIVEMODE CY_GPIO_DM_STRONG
#define CYBSP_OSPI_RAM_D4_INIT_DRIVESTATE 1
#ifndef ioss_0_port_4_pin_4_HSIOM
    #define ioss_0_port_4_pin_4_HSIOM HSIOM_SEL_ACT_15
#endif
#define CYBSP_OSPI_RAM_D4_HSIOM ioss_0_port_4_pin_4_HSIOM
#define CYBSP_OSPI_RAM_D4_IRQ ioss_interrupts_gpio_4_IRQn

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
#define CYBSP_OSPI_RAM_D4_HAL_PORT_PIN P4_4
#define CYBSP_OSPI_RAM_D4 P4_4
#define CYBSP_OSPI_RAM_D4_HAL_IRQ CYHAL_GPIO_IRQ_NONE
#define CYBSP_OSPI_RAM_D4_HAL_DIR CYHAL_GPIO_DIR_BIDIRECTIONAL 
#define CYBSP_OSPI_RAM_D4_HAL_DRIVEMODE CYHAL_GPIO_DRIVE_STRONG
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

#define CYBSP_OSPI_RAM_D5_ENABLED 1U
#define CYBSP_OSPI_RAM_D5_PORT (GPIO_PRT_Type*)SMIF1_CORE_SMIF_GPIO_SMIF_PRT0
#define CYBSP_OSPI_RAM_D5_PORT_NUM 4U
#define CYBSP_OSPI_RAM_D5_PIN 5U
#define CYBSP_OSPI_RAM_D5_NUM 5U
#define CYBSP_OSPI_RAM_D5_DRIVEMODE CY_GPIO_DM_STRONG
#define CYBSP_OSPI_RAM_D5_INIT_DRIVESTATE 1
#ifndef ioss_0_port_4_pin_5_HSIOM
    #define ioss_0_port_4_pin_5_HSIOM HSIOM_SEL_ACT_15
#endif
#define CYBSP_OSPI_RAM_D5_HSIOM ioss_0_port_4_pin_5_HSIOM
#define CYBSP_OSPI_RAM_D5_IRQ ioss_interrupts_gpio_4_IRQn

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
#define CYBSP_OSPI_RAM_D5_HAL_PORT_PIN P4_5
#define CYBSP_OSPI_RAM_D5 P4_5
#define CYBSP_OSPI_RAM_D5_HAL_IRQ CYHAL_GPIO_IRQ_NONE
#define CYBSP_OSPI_RAM_D5_HAL_DIR CYHAL_GPIO_DIR_BIDIRECTIONAL 
#define CYBSP_OSPI_RAM_D5_HAL_DRIVEMODE CYHAL_GPIO_DRIVE_STRONG
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

#define CYBSP_OSPI_RAM_D6_ENABLED 1U
#define CYBSP_OSPI_RAM_D6_PORT (GPIO_PRT_Type*)SMIF1_CORE_SMIF_GPIO_SMIF_PRT0
#define CYBSP_OSPI_RAM_D6_PORT_NUM 4U
#define CYBSP_OSPI_RAM_D6_PIN 6U
#define CYBSP_OSPI_RAM_D6_NUM 6U
#define CYBSP_OSPI_RAM_D6_DRIVEMODE CY_GPIO_DM_STRONG
#define CYBSP_OSPI_RAM_D6_INIT_DRIVESTATE 1
#ifndef ioss_0_port_4_pin_6_HSIOM
    #define ioss_0_port_4_pin_6_HSIOM HSIOM_SEL_ACT_15
#endif
#define CYBSP_OSPI_RAM_D6_HSIOM ioss_0_port_4_pin_6_HSIOM
#define CYBSP_OSPI_RAM_D6_IRQ ioss_interrupts_gpio_4_IRQn

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
#define CYBSP_OSPI_RAM_D6_HAL_PORT_PIN P4_6
#define CYBSP_OSPI_RAM_D6 P4_6
#define CYBSP_OSPI_RAM_D6_HAL_IRQ CYHAL_GPIO_IRQ_NONE
#define CYBSP_OSPI_RAM_D6_HAL_DIR CYHAL_GPIO_DIR_BIDIRECTIONAL 
#define CYBSP_OSPI_RAM_D6_HAL_DRIVEMODE CYHAL_GPIO_DRIVE_STRONG
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

#define CYBSP_OSPI_RAM_D7_ENABLED 1U
#define CYBSP_OSPI_RAM_D7_PORT (GPIO_PRT_Type*)SMIF1_CORE_SMIF_GPIO_SMIF_PRT0
#define CYBSP_OSPI_RAM_D7_PORT_NUM 4U
#define CYBSP_OSPI_RAM_D7_PIN 7U
#define CYBSP_OSPI_RAM_D7_NUM 7U
#define CYBSP_OSPI_RAM_D7_DRIVEMODE CY_GPIO_DM_STRONG
#define CYBSP_OSPI_RAM_D7_INIT_DRIVESTATE 1
#ifndef ioss_0_port_4_pin_7_HSIOM
    #define ioss_0_port_4_pin_7_HSIOM HSIOM_SEL_ACT_15
#endif
#define CYBSP_OSPI_RAM_D7_HSIOM ioss_0_port_4_pin_7_HSIOM
#define CYBSP_OSPI_RAM_D7_IRQ ioss_interrupts_gpio_4_IRQn

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
#define CYBSP_OSPI_RAM_D7_HAL_PORT_PIN P4_7
#define CYBSP_OSPI_RAM_D7 P4_7
#define CYBSP_OSPI_RAM_D7_HAL_IRQ CYHAL_GPIO_IRQ_NONE
#define CYBSP_OSPI_RAM_D7_HAL_DIR CYHAL_GPIO_DIR_BIDIRECTIONAL 
#define CYBSP_OSPI_RAM_D7_HAL_DRIVEMODE CYHAL_GPIO_DRIVE_STRONG
#define CYBSP_USB_HOST_ENABLE_POWER (P5_0)
#define CYBSP_SWJ_TDO (P6_0)
#define CYBSP_SWJ_TDI (P6_1)
#define CYBSP_SWJ_SWDIO (P6_2)
#define CYBSP_SWJ_TMS CYBSP_SWJ_SWDIO
#define CYBSP_SWDCK (P6_3)
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

#define CYBSP_WIFI_WL_REG_ON_ENABLED 1U
#define CYBSP_WIFI_WL_REG_ON_PORT GPIO_PRT6
#define CYBSP_WIFI_WL_REG_ON_PORT_NUM 6U
#define CYBSP_WIFI_WL_REG_ON_PIN 4U
#define CYBSP_WIFI_WL_REG_ON_NUM 4U
#define CYBSP_WIFI_WL_REG_ON_DRIVEMODE CY_GPIO_DM_OD_DRIVESLOW
#define CYBSP_WIFI_WL_REG_ON_INIT_DRIVESTATE 1
#ifndef ioss_0_port_6_pin_4_HSIOM
    #define ioss_0_port_6_pin_4_HSIOM HSIOM_SEL_GPIO
#endif
#define CYBSP_WIFI_WL_REG_ON_HSIOM ioss_0_port_6_pin_4_HSIOM
#define CYBSP_WIFI_WL_REG_ON_IRQ ioss_interrupts_gpio_6_IRQn

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
#define CYBSP_WIFI_WL_REG_ON_HAL_PORT_PIN P6_4
#define CYBSP_WIFI_WL_REG_ON P6_4
#define CYBSP_WIFI_WL_REG_ON_HAL_IRQ CYHAL_GPIO_IRQ_NONE
#define CYBSP_WIFI_WL_REG_ON_HAL_DIR CYHAL_GPIO_DIR_BIDIRECTIONAL 
#define CYBSP_WIFI_WL_REG_ON_HAL_DRIVEMODE CYHAL_GPIO_DRIVE_OPENDRAINDRIVESLOW
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

#define CYBSP_DEBUG_UART_RX_ENABLED 1U
#define CYBSP_DEBUG_UART_RX_PORT GPIO_PRT6
#define CYBSP_DEBUG_UART_RX_PORT_NUM 6U
#define CYBSP_DEBUG_UART_RX_PIN 5U
#define CYBSP_DEBUG_UART_RX_NUM 5U
#define CYBSP_DEBUG_UART_RX_DRIVEMODE CY_GPIO_DM_HIGHZ
#define CYBSP_DEBUG_UART_RX_INIT_DRIVESTATE 1
#ifndef ioss_0_port_6_pin_5_HSIOM
    #define ioss_0_port_6_pin_5_HSIOM HSIOM_SEL_GPIO
#endif
#define CYBSP_DEBUG_UART_RX_HSIOM ioss_0_port_6_pin_5_HSIOM
#define CYBSP_DEBUG_UART_RX_IRQ ioss_interrupts_gpio_6_IRQn

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
#define CYBSP_DEBUG_UART_RX_HAL_PORT_PIN P6_5
#define CYBSP_DEBUG_UART_RX P6_5
#define CYBSP_DEBUG_UART_RX_HAL_IRQ CYHAL_GPIO_IRQ_NONE
#define CYBSP_DEBUG_UART_RX_HAL_DIR CYHAL_GPIO_DIR_INPUT 
#define CYBSP_DEBUG_UART_RX_HAL_DRIVEMODE CYHAL_GPIO_DRIVE_NONE
#define CYBSP_WL_BT_DEV_WAKE (P6_6)
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

#define CYBSP_DEBUG_UART_TX_ENABLED 1U
#define CYBSP_DEBUG_UART_TX_PORT GPIO_PRT6
#define CYBSP_DEBUG_UART_TX_PORT_NUM 6U
#define CYBSP_DEBUG_UART_TX_PIN 7U
#define CYBSP_DEBUG_UART_TX_NUM 7U
#define CYBSP_DEBUG_UART_TX_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define CYBSP_DEBUG_UART_TX_INIT_DRIVESTATE 1
#ifndef ioss_0_port_6_pin_7_HSIOM
    #define ioss_0_port_6_pin_7_HSIOM HSIOM_SEL_GPIO
#endif
#define CYBSP_DEBUG_UART_TX_HSIOM ioss_0_port_6_pin_7_HSIOM
#define CYBSP_DEBUG_UART_TX_IRQ ioss_interrupts_gpio_6_IRQn

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
#define CYBSP_DEBUG_UART_TX_HAL_PORT_PIN P6_7
#define CYBSP_DEBUG_UART_TX P6_7
#define CYBSP_DEBUG_UART_TX_HAL_IRQ CYHAL_GPIO_IRQ_NONE
#define CYBSP_DEBUG_UART_TX_HAL_DIR CYHAL_GPIO_DIR_OUTPUT 
#define CYBSP_DEBUG_UART_TX_HAL_DRIVEMODE CYHAL_GPIO_DRIVE_STRONG
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

#define CYBSP_SDHC_CMD_ENABLED 1U
#define CYBSP_SDHC_CMD_PORT GPIO_PRT7
#define CYBSP_SDHC_CMD_PORT_NUM 7U
#define CYBSP_SDHC_CMD_PIN 0U
#define CYBSP_SDHC_CMD_NUM 0U
#define CYBSP_SDHC_CMD_DRIVEMODE CY_GPIO_DM_STRONG
#define CYBSP_SDHC_CMD_INIT_DRIVESTATE 1
#ifndef ioss_0_port_7_pin_0_HSIOM
    #define ioss_0_port_7_pin_0_HSIOM HSIOM_SEL_GPIO
#endif
#define CYBSP_SDHC_CMD_HSIOM ioss_0_port_7_pin_0_HSIOM
#define CYBSP_SDHC_CMD_IRQ ioss_interrupts_gpio_7_IRQn

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
#define CYBSP_SDHC_CMD_HAL_PORT_PIN P7_0
#define CYBSP_SDHC_CMD P7_0
#define CYBSP_SDHC_CMD_HAL_IRQ CYHAL_GPIO_IRQ_NONE
#define CYBSP_SDHC_CMD_HAL_DIR CYHAL_GPIO_DIR_BIDIRECTIONAL 
#define CYBSP_SDHC_CMD_HAL_DRIVEMODE CYHAL_GPIO_DRIVE_STRONG
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

#define CYBSP_SDHC_CLK_ENABLED 1U
#define CYBSP_SDHC_CLK_PORT GPIO_PRT7
#define CYBSP_SDHC_CLK_PORT_NUM 7U
#define CYBSP_SDHC_CLK_PIN 1U
#define CYBSP_SDHC_CLK_NUM 1U
#define CYBSP_SDHC_CLK_DRIVEMODE CY_GPIO_DM_STRONG
#define CYBSP_SDHC_CLK_INIT_DRIVESTATE 1
#ifndef ioss_0_port_7_pin_1_HSIOM
    #define ioss_0_port_7_pin_1_HSIOM HSIOM_SEL_GPIO
#endif
#define CYBSP_SDHC_CLK_HSIOM ioss_0_port_7_pin_1_HSIOM
#define CYBSP_SDHC_CLK_IRQ ioss_interrupts_gpio_7_IRQn

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
#define CYBSP_SDHC_CLK_HAL_PORT_PIN P7_1
#define CYBSP_SDHC_CLK P7_1
#define CYBSP_SDHC_CLK_HAL_IRQ CYHAL_GPIO_IRQ_NONE
#define CYBSP_SDHC_CLK_HAL_DIR CYHAL_GPIO_DIR_BIDIRECTIONAL 
#define CYBSP_SDHC_CLK_HAL_DRIVEMODE CYHAL_GPIO_DRIVE_STRONG
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

#define CYBSP_USER_BTN3_ENABLED 1U
#define CYBSP_SW5_ENABLED CYBSP_USER_BTN3_ENABLED
#define CYBSP_USER_BTN3_PORT GPIO_PRT7
#define CYBSP_SW5_PORT CYBSP_USER_BTN3_PORT
#define CYBSP_USER_BTN3_PORT_NUM 7U
#define CYBSP_SW5_PORT_NUM CYBSP_USER_BTN3_PORT_NUM
#define CYBSP_USER_BTN3_PIN 2U
#define CYBSP_SW5_PIN CYBSP_USER_BTN3_PIN
#define CYBSP_USER_BTN3_NUM 2U
#define CYBSP_SW5_NUM CYBSP_USER_BTN3_NUM
#define CYBSP_USER_BTN3_DRIVEMODE CY_GPIO_DM_PULLUP
#define CYBSP_SW5_DRIVEMODE CYBSP_USER_BTN3_DRIVEMODE
#define CYBSP_USER_BTN3_INIT_DRIVESTATE 1
#define CYBSP_SW5_INIT_DRIVESTATE CYBSP_USER_BTN3_INIT_DRIVESTATE
#ifndef ioss_0_port_7_pin_2_HSIOM
    #define ioss_0_port_7_pin_2_HSIOM HSIOM_SEL_GPIO
#endif
#define CYBSP_USER_BTN3_HSIOM ioss_0_port_7_pin_2_HSIOM
#define CYBSP_SW5_HSIOM CYBSP_USER_BTN3_HSIOM
#define CYBSP_USER_BTN3_IRQ ioss_interrupts_gpio_7_IRQn
#define CYBSP_SW5_IRQ CYBSP_USER_BTN3_IRQ

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
#define CYBSP_USER_BTN3_HAL_PORT_PIN P7_2
#define CYBSP_SW5_HAL_PORT_PIN CYBSP_USER_BTN3_HAL_PORT_PIN
#define CYBSP_USER_BTN3 P7_2
#define CYBSP_SW5 CYBSP_USER_BTN3
#define CYBSP_USER_BTN3_HAL_IRQ CYHAL_GPIO_IRQ_NONE
#define CYBSP_SW5_HAL_IRQ CYBSP_USER_BTN3_HAL_IRQ
#define CYBSP_USER_BTN3_HAL_DIR CYHAL_GPIO_DIR_BIDIRECTIONAL 
#define CYBSP_SW5_HAL_DIR CYBSP_USER_BTN3_HAL_DIR
#define CYBSP_USER_BTN3_HAL_DRIVEMODE CYHAL_GPIO_DRIVE_PULLUP
#define CYBSP_SW5_HAL_DRIVEMODE CYBSP_USER_BTN3_HAL_DRIVEMODE
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

#define CYBSP_SDHC_IO0_ENABLED 1U
#define CYBSP_SDHC_IO0_PORT GPIO_PRT7
#define CYBSP_SDHC_IO0_PORT_NUM 7U
#define CYBSP_SDHC_IO0_PIN 3U
#define CYBSP_SDHC_IO0_NUM 3U
#define CYBSP_SDHC_IO0_DRIVEMODE CY_GPIO_DM_STRONG
#define CYBSP_SDHC_IO0_INIT_DRIVESTATE 1
#ifndef ioss_0_port_7_pin_3_HSIOM
    #define ioss_0_port_7_pin_3_HSIOM HSIOM_SEL_GPIO
#endif
#define CYBSP_SDHC_IO0_HSIOM ioss_0_port_7_pin_3_HSIOM
#define CYBSP_SDHC_IO0_IRQ ioss_interrupts_gpio_7_IRQn

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
#define CYBSP_SDHC_IO0_HAL_PORT_PIN P7_3
#define CYBSP_SDHC_IO0 P7_3
#define CYBSP_SDHC_IO0_HAL_IRQ CYHAL_GPIO_IRQ_NONE
#define CYBSP_SDHC_IO0_HAL_DIR CYHAL_GPIO_DIR_BIDIRECTIONAL 
#define CYBSP_SDHC_IO0_HAL_DRIVEMODE CYHAL_GPIO_DRIVE_STRONG
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

#define CYBSP_EXT_CLK_ENABLED 1U
#define CYBSP_EXT_CLK_PORT GPIO_PRT7
#define CYBSP_EXT_CLK_PORT_NUM 7U
#define CYBSP_EXT_CLK_PIN 4U
#define CYBSP_EXT_CLK_NUM 4U
#define CYBSP_EXT_CLK_DRIVEMODE CY_GPIO_DM_ANALOG
#define CYBSP_EXT_CLK_INIT_DRIVESTATE 1
#ifndef ioss_0_port_7_pin_4_HSIOM
    #define ioss_0_port_7_pin_4_HSIOM HSIOM_SEL_GPIO
#endif
#define CYBSP_EXT_CLK_HSIOM ioss_0_port_7_pin_4_HSIOM
#define CYBSP_EXT_CLK_IRQ ioss_interrupts_gpio_7_IRQn

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
#define CYBSP_EXT_CLK_HAL_PORT_PIN P7_4
#define CYBSP_EXT_CLK P7_4
#define CYBSP_EXT_CLK_HAL_IRQ CYHAL_GPIO_IRQ_NONE
#define CYBSP_EXT_CLK_HAL_DIR CYHAL_GPIO_DIR_INPUT 
#define CYBSP_EXT_CLK_HAL_DRIVEMODE CYHAL_GPIO_DRIVE_ANALOG
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

#define CYBSP_SDHC_IO1_ENABLED 1U
#define CYBSP_SDHC_IO1_PORT GPIO_PRT7
#define CYBSP_SDHC_IO1_PORT_NUM 7U
#define CYBSP_SDHC_IO1_PIN 5U
#define CYBSP_SDHC_IO1_NUM 5U
#define CYBSP_SDHC_IO1_DRIVEMODE CY_GPIO_DM_STRONG
#define CYBSP_SDHC_IO1_INIT_DRIVESTATE 1
#ifndef ioss_0_port_7_pin_5_HSIOM
    #define ioss_0_port_7_pin_5_HSIOM HSIOM_SEL_GPIO
#endif
#define CYBSP_SDHC_IO1_HSIOM ioss_0_port_7_pin_5_HSIOM
#define CYBSP_SDHC_IO1_IRQ ioss_interrupts_gpio_7_IRQn

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
#define CYBSP_SDHC_IO1_HAL_PORT_PIN P7_5
#define CYBSP_SDHC_IO1 P7_5
#define CYBSP_SDHC_IO1_HAL_IRQ CYHAL_GPIO_IRQ_NONE
#define CYBSP_SDHC_IO1_HAL_DIR CYHAL_GPIO_DIR_BIDIRECTIONAL 
#define CYBSP_SDHC_IO1_HAL_DRIVEMODE CYHAL_GPIO_DRIVE_STRONG
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

#define CYBSP_SDHC_IO2_ENABLED 1U
#define CYBSP_SDHC_IO2_PORT GPIO_PRT7
#define CYBSP_SDHC_IO2_PORT_NUM 7U
#define CYBSP_SDHC_IO2_PIN 6U
#define CYBSP_SDHC_IO2_NUM 6U
#define CYBSP_SDHC_IO2_DRIVEMODE CY_GPIO_DM_STRONG
#define CYBSP_SDHC_IO2_INIT_DRIVESTATE 1
#ifndef ioss_0_port_7_pin_6_HSIOM
    #define ioss_0_port_7_pin_6_HSIOM HSIOM_SEL_GPIO
#endif
#define CYBSP_SDHC_IO2_HSIOM ioss_0_port_7_pin_6_HSIOM
#define CYBSP_SDHC_IO2_IRQ ioss_interrupts_gpio_7_IRQn

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
#define CYBSP_SDHC_IO2_HAL_PORT_PIN P7_6
#define CYBSP_SDHC_IO2 P7_6
#define CYBSP_SDHC_IO2_HAL_IRQ CYHAL_GPIO_IRQ_NONE
#define CYBSP_SDHC_IO2_HAL_DIR CYHAL_GPIO_DIR_BIDIRECTIONAL 
#define CYBSP_SDHC_IO2_HAL_DRIVEMODE CYHAL_GPIO_DRIVE_STRONG
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

#define CYBSP_SDHC_IO3_ENABLED 1U
#define CYBSP_SDHC_IO3_PORT GPIO_PRT7
#define CYBSP_SDHC_IO3_PORT_NUM 7U
#define CYBSP_SDHC_IO3_PIN 7U
#define CYBSP_SDHC_IO3_NUM 7U
#define CYBSP_SDHC_IO3_DRIVEMODE CY_GPIO_DM_STRONG
#define CYBSP_SDHC_IO3_INIT_DRIVESTATE 1
#ifndef ioss_0_port_7_pin_7_HSIOM
    #define ioss_0_port_7_pin_7_HSIOM HSIOM_SEL_GPIO
#endif
#define CYBSP_SDHC_IO3_HSIOM ioss_0_port_7_pin_7_HSIOM
#define CYBSP_SDHC_IO3_IRQ ioss_interrupts_gpio_7_IRQn

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
#define CYBSP_SDHC_IO3_HAL_PORT_PIN P7_7
#define CYBSP_SDHC_IO3 P7_7
#define CYBSP_SDHC_IO3_HAL_IRQ CYHAL_GPIO_IRQ_NONE
#define CYBSP_SDHC_IO3_HAL_DIR CYHAL_GPIO_DIR_BIDIRECTIONAL 
#define CYBSP_SDHC_IO3_HAL_DRIVEMODE CYHAL_GPIO_DRIVE_STRONG
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

#define CYBSP_I2C_SCL_ENABLED 1U
#define CYBSP_I2C_SCL_1V8_ENABLED CYBSP_I2C_SCL_ENABLED
#define CYBSP_I2C_SCL_PORT GPIO_PRT8
#define CYBSP_I2C_SCL_1V8_PORT CYBSP_I2C_SCL_PORT
#define CYBSP_I2C_SCL_PORT_NUM 8U
#define CYBSP_I2C_SCL_1V8_PORT_NUM CYBSP_I2C_SCL_PORT_NUM
#define CYBSP_I2C_SCL_PIN 0U
#define CYBSP_I2C_SCL_1V8_PIN CYBSP_I2C_SCL_PIN
#define CYBSP_I2C_SCL_NUM 0U
#define CYBSP_I2C_SCL_1V8_NUM CYBSP_I2C_SCL_NUM
#define CYBSP_I2C_SCL_DRIVEMODE CY_GPIO_DM_OD_DRIVESLOW
#define CYBSP_I2C_SCL_1V8_DRIVEMODE CYBSP_I2C_SCL_DRIVEMODE
#define CYBSP_I2C_SCL_INIT_DRIVESTATE 1
#define CYBSP_I2C_SCL_1V8_INIT_DRIVESTATE CYBSP_I2C_SCL_INIT_DRIVESTATE
#ifndef ioss_0_port_8_pin_0_HSIOM
    #define ioss_0_port_8_pin_0_HSIOM HSIOM_SEL_GPIO
#endif
#define CYBSP_I2C_SCL_HSIOM ioss_0_port_8_pin_0_HSIOM
#define CYBSP_I2C_SCL_1V8_HSIOM CYBSP_I2C_SCL_HSIOM
#define CYBSP_I2C_SCL_IRQ ioss_interrupts_gpio_8_IRQn
#define CYBSP_I2C_SCL_1V8_IRQ CYBSP_I2C_SCL_IRQ

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
#define CYBSP_I2C_SCL_HAL_PORT_PIN P8_0
#define CYBSP_I2C_SCL_1V8_HAL_PORT_PIN CYBSP_I2C_SCL_HAL_PORT_PIN
#define CYBSP_I2C_SCL P8_0
#define CYBSP_I2C_SCL_1V8 CYBSP_I2C_SCL
#define CYBSP_I2C_SCL_HAL_IRQ CYHAL_GPIO_IRQ_NONE
#define CYBSP_I2C_SCL_1V8_HAL_IRQ CYBSP_I2C_SCL_HAL_IRQ
#define CYBSP_I2C_SCL_HAL_DIR CYHAL_GPIO_DIR_BIDIRECTIONAL 
#define CYBSP_I2C_SCL_1V8_HAL_DIR CYBSP_I2C_SCL_HAL_DIR
#define CYBSP_I2C_SCL_HAL_DRIVEMODE CYHAL_GPIO_DRIVE_OPENDRAINDRIVESLOW
#define CYBSP_I2C_SCL_1V8_HAL_DRIVEMODE CYBSP_I2C_SCL_HAL_DRIVEMODE
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

#define CYBSP_I2C_SDA_ENABLED 1U
#define CYBSP_I2C_SDA_1V8_ENABLED CYBSP_I2C_SDA_ENABLED
#define CYBSP_I2C_SDA_PORT GPIO_PRT8
#define CYBSP_I2C_SDA_1V8_PORT CYBSP_I2C_SDA_PORT
#define CYBSP_I2C_SDA_PORT_NUM 8U
#define CYBSP_I2C_SDA_1V8_PORT_NUM CYBSP_I2C_SDA_PORT_NUM
#define CYBSP_I2C_SDA_PIN 1U
#define CYBSP_I2C_SDA_1V8_PIN CYBSP_I2C_SDA_PIN
#define CYBSP_I2C_SDA_NUM 1U
#define CYBSP_I2C_SDA_1V8_NUM CYBSP_I2C_SDA_NUM
#define CYBSP_I2C_SDA_DRIVEMODE CY_GPIO_DM_OD_DRIVESLOW
#define CYBSP_I2C_SDA_1V8_DRIVEMODE CYBSP_I2C_SDA_DRIVEMODE
#define CYBSP_I2C_SDA_INIT_DRIVESTATE 1
#define CYBSP_I2C_SDA_1V8_INIT_DRIVESTATE CYBSP_I2C_SDA_INIT_DRIVESTATE
#ifndef ioss_0_port_8_pin_1_HSIOM
    #define ioss_0_port_8_pin_1_HSIOM HSIOM_SEL_GPIO
#endif
#define CYBSP_I2C_SDA_HSIOM ioss_0_port_8_pin_1_HSIOM
#define CYBSP_I2C_SDA_1V8_HSIOM CYBSP_I2C_SDA_HSIOM
#define CYBSP_I2C_SDA_IRQ ioss_interrupts_gpio_8_IRQn
#define CYBSP_I2C_SDA_1V8_IRQ CYBSP_I2C_SDA_IRQ

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
#define CYBSP_I2C_SDA_HAL_PORT_PIN P8_1
#define CYBSP_I2C_SDA_1V8_HAL_PORT_PIN CYBSP_I2C_SDA_HAL_PORT_PIN
#define CYBSP_I2C_SDA P8_1
#define CYBSP_I2C_SDA_1V8 CYBSP_I2C_SDA
#define CYBSP_I2C_SDA_HAL_IRQ CYHAL_GPIO_IRQ_NONE
#define CYBSP_I2C_SDA_1V8_HAL_IRQ CYBSP_I2C_SDA_HAL_IRQ
#define CYBSP_I2C_SDA_HAL_DIR CYHAL_GPIO_DIR_BIDIRECTIONAL 
#define CYBSP_I2C_SDA_1V8_HAL_DIR CYBSP_I2C_SDA_HAL_DIR
#define CYBSP_I2C_SDA_HAL_DRIVEMODE CYHAL_GPIO_DRIVE_OPENDRAINDRIVESLOW
#define CYBSP_I2C_SDA_1V8_HAL_DRIVEMODE CYBSP_I2C_SDA_HAL_DRIVEMODE
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

#define CYBSP_BT_POWER_ENABLED 1U
#define CYBSP_BT_POWER_PORT GPIO_PRT8
#define CYBSP_BT_POWER_PORT_NUM 8U
#define CYBSP_BT_POWER_PIN 2U
#define CYBSP_BT_POWER_NUM 2U
#define CYBSP_BT_POWER_DRIVEMODE CY_GPIO_DM_PULLUP
#define CYBSP_BT_POWER_INIT_DRIVESTATE 1
#ifndef ioss_0_port_8_pin_2_HSIOM
    #define ioss_0_port_8_pin_2_HSIOM HSIOM_SEL_GPIO
#endif
#define CYBSP_BT_POWER_HSIOM ioss_0_port_8_pin_2_HSIOM
#define CYBSP_BT_POWER_IRQ ioss_interrupts_gpio_8_IRQn

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
#define CYBSP_BT_POWER_HAL_PORT_PIN P8_2
#define CYBSP_BT_POWER P8_2
#define CYBSP_BT_POWER_HAL_IRQ CYHAL_GPIO_IRQ_NONE
#define CYBSP_BT_POWER_HAL_DIR CYHAL_GPIO_DIR_BIDIRECTIONAL 
#define CYBSP_BT_POWER_HAL_DRIVEMODE CYHAL_GPIO_DRIVE_PULLUP
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

#define CYBSP_USER_BTN1_ENABLED 1U
#define CYBSP_USER_BTN_ENABLED CYBSP_USER_BTN1_ENABLED
#define CYBSP_SW3_ENABLED CYBSP_USER_BTN1_ENABLED
#define CYBSP_USER_BTN1_PORT GPIO_PRT8
#define CYBSP_USER_BTN_PORT CYBSP_USER_BTN1_PORT
#define CYBSP_SW3_PORT CYBSP_USER_BTN1_PORT
#define CYBSP_USER_BTN1_PORT_NUM 8U
#define CYBSP_USER_BTN_PORT_NUM CYBSP_USER_BTN1_PORT_NUM
#define CYBSP_SW3_PORT_NUM CYBSP_USER_BTN1_PORT_NUM
#define CYBSP_USER_BTN1_PIN 3U
#define CYBSP_USER_BTN_PIN CYBSP_USER_BTN1_PIN
#define CYBSP_SW3_PIN CYBSP_USER_BTN1_PIN
#define CYBSP_USER_BTN1_NUM 3U
#define CYBSP_USER_BTN_NUM CYBSP_USER_BTN1_NUM
#define CYBSP_SW3_NUM CYBSP_USER_BTN1_NUM
#define CYBSP_USER_BTN1_DRIVEMODE CY_GPIO_DM_PULLUP
#define CYBSP_USER_BTN_DRIVEMODE CYBSP_USER_BTN1_DRIVEMODE
#define CYBSP_SW3_DRIVEMODE CYBSP_USER_BTN1_DRIVEMODE
#define CYBSP_USER_BTN1_INIT_DRIVESTATE 1
#define CYBSP_USER_BTN_INIT_DRIVESTATE CYBSP_USER_BTN1_INIT_DRIVESTATE
#define CYBSP_SW3_INIT_DRIVESTATE CYBSP_USER_BTN1_INIT_DRIVESTATE
#ifndef ioss_0_port_8_pin_3_HSIOM
    #define ioss_0_port_8_pin_3_HSIOM HSIOM_SEL_GPIO
#endif
#define CYBSP_USER_BTN1_HSIOM ioss_0_port_8_pin_3_HSIOM
#define CYBSP_USER_BTN_HSIOM CYBSP_USER_BTN1_HSIOM
#define CYBSP_SW3_HSIOM CYBSP_USER_BTN1_HSIOM
#define CYBSP_USER_BTN1_IRQ ioss_interrupts_gpio_8_IRQn
#define CYBSP_USER_BTN_IRQ CYBSP_USER_BTN1_IRQ
#define CYBSP_SW3_IRQ CYBSP_USER_BTN1_IRQ

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
#define CYBSP_USER_BTN1_HAL_PORT_PIN P8_3
#define CYBSP_USER_BTN_HAL_PORT_PIN CYBSP_USER_BTN1_HAL_PORT_PIN
#define CYBSP_SW3_HAL_PORT_PIN CYBSP_USER_BTN1_HAL_PORT_PIN
#define CYBSP_USER_BTN1 P8_3
#define CYBSP_USER_BTN CYBSP_USER_BTN1
#define CYBSP_SW3 CYBSP_USER_BTN1
#define CYBSP_USER_BTN1_HAL_IRQ CYHAL_GPIO_IRQ_FALL
#define CYBSP_USER_BTN_HAL_IRQ CYBSP_USER_BTN1_HAL_IRQ
#define CYBSP_SW3_HAL_IRQ CYBSP_USER_BTN1_HAL_IRQ
#define CYBSP_USER_BTN1_HAL_DIR CYHAL_GPIO_DIR_BIDIRECTIONAL 
#define CYBSP_USER_BTN_HAL_DIR CYBSP_USER_BTN1_HAL_DIR
#define CYBSP_SW3_HAL_DIR CYBSP_USER_BTN1_HAL_DIR
#define CYBSP_USER_BTN1_HAL_DRIVEMODE CYHAL_GPIO_DRIVE_PULLUP
#define CYBSP_USER_BTN_HAL_DRIVEMODE CYBSP_USER_BTN1_HAL_DRIVEMODE
#define CYBSP_SW3_HAL_DRIVEMODE CYBSP_USER_BTN1_HAL_DRIVEMODE
#define CYBSP_INT_IMU (P8_4)
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

#define CYBSP_PDM_CLK_ENABLED 1U
#define CYBSP_PDM_CLK_PORT GPIO_PRT8
#define CYBSP_PDM_CLK_PORT_NUM 8U
#define CYBSP_PDM_CLK_PIN 5U
#define CYBSP_PDM_CLK_NUM 5U
#define CYBSP_PDM_CLK_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define CYBSP_PDM_CLK_INIT_DRIVESTATE 1
#ifndef ioss_0_port_8_pin_5_HSIOM
    #define ioss_0_port_8_pin_5_HSIOM HSIOM_SEL_GPIO
#endif
#define CYBSP_PDM_CLK_HSIOM ioss_0_port_8_pin_5_HSIOM
#define CYBSP_PDM_CLK_IRQ ioss_interrupts_gpio_8_IRQn

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
#define CYBSP_PDM_CLK_HAL_PORT_PIN P8_5
#define CYBSP_PDM_CLK P8_5
#define CYBSP_PDM_CLK_HAL_IRQ CYHAL_GPIO_IRQ_NONE
#define CYBSP_PDM_CLK_HAL_DIR CYHAL_GPIO_DIR_OUTPUT 
#define CYBSP_PDM_CLK_HAL_DRIVEMODE CYHAL_GPIO_DRIVE_STRONG
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

#define CYBSP_PDM_DATA_ENABLED 1U
#define CYBSP_PDM_DATA_PORT GPIO_PRT8
#define CYBSP_PDM_DATA_PORT_NUM 8U
#define CYBSP_PDM_DATA_PIN 6U
#define CYBSP_PDM_DATA_NUM 6U
#define CYBSP_PDM_DATA_DRIVEMODE CY_GPIO_DM_HIGHZ
#define CYBSP_PDM_DATA_INIT_DRIVESTATE 1
#ifndef ioss_0_port_8_pin_6_HSIOM
    #define ioss_0_port_8_pin_6_HSIOM HSIOM_SEL_GPIO
#endif
#define CYBSP_PDM_DATA_HSIOM ioss_0_port_8_pin_6_HSIOM
#define CYBSP_PDM_DATA_IRQ ioss_interrupts_gpio_8_IRQn

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
#define CYBSP_PDM_DATA_HAL_PORT_PIN P8_6
#define CYBSP_PDM_DATA P8_6
#define CYBSP_PDM_DATA_HAL_IRQ CYHAL_GPIO_IRQ_NONE
#define CYBSP_PDM_DATA_HAL_DIR CYHAL_GPIO_DIR_INPUT 
#define CYBSP_PDM_DATA_HAL_DRIVEMODE CYHAL_GPIO_DRIVE_NONE
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

#define CYBSP_USER_BTN2_ENABLED 1U
#define CYBSP_SW4_ENABLED CYBSP_USER_BTN2_ENABLED
#define CYBSP_USER_BTN2_PORT GPIO_PRT8
#define CYBSP_SW4_PORT CYBSP_USER_BTN2_PORT
#define CYBSP_USER_BTN2_PORT_NUM 8U
#define CYBSP_SW4_PORT_NUM CYBSP_USER_BTN2_PORT_NUM
#define CYBSP_USER_BTN2_PIN 7U
#define CYBSP_SW4_PIN CYBSP_USER_BTN2_PIN
#define CYBSP_USER_BTN2_NUM 7U
#define CYBSP_SW4_NUM CYBSP_USER_BTN2_NUM
#define CYBSP_USER_BTN2_DRIVEMODE CY_GPIO_DM_PULLUP
#define CYBSP_SW4_DRIVEMODE CYBSP_USER_BTN2_DRIVEMODE
#define CYBSP_USER_BTN2_INIT_DRIVESTATE 1
#define CYBSP_SW4_INIT_DRIVESTATE CYBSP_USER_BTN2_INIT_DRIVESTATE
#ifndef ioss_0_port_8_pin_7_HSIOM
    #define ioss_0_port_8_pin_7_HSIOM HSIOM_SEL_GPIO
#endif
#define CYBSP_USER_BTN2_HSIOM ioss_0_port_8_pin_7_HSIOM
#define CYBSP_SW4_HSIOM CYBSP_USER_BTN2_HSIOM
#define CYBSP_USER_BTN2_IRQ ioss_interrupts_gpio_8_IRQn
#define CYBSP_SW4_IRQ CYBSP_USER_BTN2_IRQ

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
#define CYBSP_USER_BTN2_HAL_PORT_PIN P8_7
#define CYBSP_SW4_HAL_PORT_PIN CYBSP_USER_BTN2_HAL_PORT_PIN
#define CYBSP_USER_BTN2 P8_7
#define CYBSP_SW4 CYBSP_USER_BTN2
#define CYBSP_USER_BTN2_HAL_IRQ CYHAL_GPIO_IRQ_FALL
#define CYBSP_SW4_HAL_IRQ CYBSP_USER_BTN2_HAL_IRQ
#define CYBSP_USER_BTN2_HAL_DIR CYHAL_GPIO_DIR_BIDIRECTIONAL 
#define CYBSP_SW4_HAL_DIR CYBSP_USER_BTN2_HAL_DIR
#define CYBSP_USER_BTN2_HAL_DRIVEMODE CYHAL_GPIO_DRIVE_PULLUP
#define CYBSP_SW4_HAL_DRIVEMODE CYBSP_USER_BTN2_HAL_DRIVEMODE
#define CYBSP_SERIAL_INT_0 (P9_0)
#define CYBSP_SERIAL_INT_1 (P9_1)
#define CYBSP_SERIAL_INT_2 (P9_2)
#define CYBSP_SERIAL_INT_3 (P9_3)
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

extern const cy_stc_gpio_pin_config_t CYBSP_RS_SPI_SS_config;

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
extern const cyhal_resource_inst_t CYBSP_RS_SPI_SS_obj;
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

extern const cy_stc_gpio_pin_config_t CYBSP_OSPI_RAM_SS_config;

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
extern const cyhal_resource_inst_t CYBSP_OSPI_RAM_SS_obj;
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

extern const cy_stc_gpio_pin_config_t CYBSP_BT_UART_RX_config;

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
extern const cyhal_resource_inst_t CYBSP_BT_UART_RX_obj;
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

extern const cy_stc_gpio_pin_config_t CYBSP_BT_UART_TX_config;

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
extern const cyhal_resource_inst_t CYBSP_BT_UART_TX_obj;
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

extern const cy_stc_gpio_pin_config_t CYBSP_BT_UART_CTS_config;

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
extern const cyhal_resource_inst_t CYBSP_BT_UART_CTS_obj;
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

extern const cy_stc_gpio_pin_config_t CYBSP_BT_UART_RTS_config;

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
extern const cyhal_resource_inst_t CYBSP_BT_UART_RTS_obj;
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

extern const cy_stc_gpio_pin_config_t CYBSP_BT_HOST_WAKE_config;

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
extern const cyhal_resource_inst_t CYBSP_BT_HOST_WAKE_obj;
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

extern const cy_stc_gpio_pin_config_t CYBSP_BT_DEVICE_WAKE_config;

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
extern const cyhal_resource_inst_t CYBSP_BT_DEVICE_WAKE_obj;
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

extern const cy_stc_gpio_pin_config_t CYBSP_WIFI_SDIO_CLK_config;

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
extern const cyhal_resource_inst_t CYBSP_WIFI_SDIO_CLK_obj;
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

extern const cy_stc_gpio_pin_config_t CYBSP_WIFI_SDIO_D0_config;

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
extern const cyhal_resource_inst_t CYBSP_WIFI_SDIO_D0_obj;
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

extern const cy_stc_gpio_pin_config_t CYBSP_WIFI_SDIO_D1_config;

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
extern const cyhal_resource_inst_t CYBSP_WIFI_SDIO_D1_obj;
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

extern const cy_stc_gpio_pin_config_t CYBSP_I2S_TX_FSYNC_config;

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
extern const cyhal_resource_inst_t CYBSP_I2S_TX_FSYNC_obj;
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

extern const cy_stc_gpio_pin_config_t CYBSP_WIFI_SDIO_D2_config;

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
extern const cyhal_resource_inst_t CYBSP_WIFI_SDIO_D2_obj;
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

extern const cy_stc_gpio_pin_config_t CYBSP_WIFI_SDIO_D3_config;

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
extern const cyhal_resource_inst_t CYBSP_WIFI_SDIO_D3_obj;
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

extern const cy_stc_gpio_pin_config_t CYBSP_WIFI_HOST_WAKE_config;

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
extern const cyhal_resource_inst_t CYBSP_WIFI_HOST_WAKE_obj;
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

extern const cy_stc_gpio_pin_config_t CYBSP_SDHC_DETECT_config;

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
extern const cyhal_resource_inst_t CYBSP_SDHC_DETECT_obj;
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

extern const cy_stc_gpio_pin_config_t CYBSP_SPI_CLK_config;

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
extern const cyhal_resource_inst_t CYBSP_SPI_CLK_obj;
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

extern const cy_stc_gpio_pin_config_t CYBSP_SPI_MOSI_config;

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
extern const cyhal_resource_inst_t CYBSP_SPI_MOSI_obj;
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

extern const cy_stc_gpio_pin_config_t CYBSP_SPI_MISO_config;

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
extern const cyhal_resource_inst_t CYBSP_SPI_MISO_obj;
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

extern const cy_stc_gpio_pin_config_t CYBSP_SPI_SS0_config;

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
extern const cyhal_resource_inst_t CYBSP_SPI_SS0_obj;
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

extern const cy_stc_gpio_pin_config_t CYBSP_SPI_SS1_config;

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
extern const cyhal_resource_inst_t CYBSP_SPI_SS1_obj;
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

extern const cy_stc_gpio_pin_config_t CYBSP_DISP_BACKLIGHT_PWM_config;

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
extern const cyhal_resource_inst_t CYBSP_DISP_BACKLIGHT_PWM_obj;
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

extern const cy_stc_gpio_pin_config_t CYBSP_I2C_SCL_3V3_config;

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
extern const cyhal_resource_inst_t CYBSP_I2C_SCL_3V3_obj;
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

extern const cy_stc_gpio_pin_config_t CYBSP_I2C_SDA_3V3_config;

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
extern const cyhal_resource_inst_t CYBSP_I2C_SDA_3V3_obj;
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

extern const cy_stc_gpio_pin_config_t CYBSP_ECO_IN_config;

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
extern const cyhal_resource_inst_t CYBSP_ECO_IN_obj;
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

extern const cy_stc_gpio_pin_config_t CYBSP_ECO_OUT_config;

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
extern const cyhal_resource_inst_t CYBSP_ECO_OUT_obj;
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

extern const cy_stc_gpio_pin_config_t CYBSP_OSPI_D0_config;

#define CYBSP_QSPI_D0_config CYBSP_OSPI_D0_config

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
extern const cyhal_resource_inst_t CYBSP_OSPI_D0_obj;
#define CYBSP_QSPI_D0_obj CYBSP_OSPI_D0_obj
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

extern const cy_stc_gpio_pin_config_t CYBSP_OSPI_D1_config;

#define CYBSP_QSPI_D1_config CYBSP_OSPI_D1_config

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
extern const cyhal_resource_inst_t CYBSP_OSPI_D1_obj;
#define CYBSP_QSPI_D1_obj CYBSP_OSPI_D1_obj
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

extern const cy_stc_gpio_pin_config_t CYBSP_OSPI_D2_config;

#define CYBSP_QSPI_D2_config CYBSP_OSPI_D2_config

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
extern const cyhal_resource_inst_t CYBSP_OSPI_D2_obj;
#define CYBSP_QSPI_D2_obj CYBSP_OSPI_D2_obj
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

extern const cy_stc_gpio_pin_config_t CYBSP_OSPI_D3_config;

#define CYBSP_QSPI_D3_config CYBSP_OSPI_D3_config

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
extern const cyhal_resource_inst_t CYBSP_OSPI_D3_obj;
#define CYBSP_QSPI_D3_obj CYBSP_OSPI_D3_obj
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

extern const cy_stc_gpio_pin_config_t CYBSP_USER_LED1_config;

#define CYBSP_USER_LED_config CYBSP_USER_LED1_config
#define CYBSP_LED_RGB_RED_config CYBSP_USER_LED1_config
#define CYBSP_LED_RED_config CYBSP_USER_LED1_config

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
extern const cyhal_resource_inst_t CYBSP_USER_LED1_obj;
#define CYBSP_USER_LED_obj CYBSP_USER_LED1_obj
#define CYBSP_LED_RGB_RED_obj CYBSP_USER_LED1_obj
#define CYBSP_LED_RED_obj CYBSP_USER_LED1_obj
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

extern const cy_stc_gpio_pin_config_t CYBSP_USER_LED2_config;

#define CYBSP_USER_LED_RGB_GREEN_config CYBSP_USER_LED2_config
#define CYBSP_LED_GREEN_config CYBSP_USER_LED2_config

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
extern const cyhal_resource_inst_t CYBSP_USER_LED2_obj;
#define CYBSP_USER_LED_RGB_GREEN_obj CYBSP_USER_LED2_obj
#define CYBSP_LED_GREEN_obj CYBSP_USER_LED2_obj
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

extern const cy_stc_gpio_pin_config_t CYBSP_USER_LED3_config;

#define CYBSP_USER_LED_RGB_BLUE_config CYBSP_USER_LED3_config
#define CYBSP_LED_BLUE_config CYBSP_USER_LED3_config

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
extern const cyhal_resource_inst_t CYBSP_USER_LED3_obj;
#define CYBSP_USER_LED_RGB_BLUE_obj CYBSP_USER_LED3_obj
#define CYBSP_LED_BLUE_obj CYBSP_USER_LED3_obj
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

extern const cy_stc_gpio_pin_config_t CYBSP_STATUS_LED1_config;

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
extern const cyhal_resource_inst_t CYBSP_STATUS_LED1_obj;
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

extern const cy_stc_gpio_pin_config_t CYBSP_STATUS_LED2_config;

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
extern const cyhal_resource_inst_t CYBSP_STATUS_LED2_obj;
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

extern const cy_stc_gpio_pin_config_t CYBSP_WIFI_SDIO_CMD_config;

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
extern const cyhal_resource_inst_t CYBSP_WIFI_SDIO_CMD_obj;
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

extern const cy_stc_gpio_pin_config_t CYBSP_I2S_TX_SD_config;

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
extern const cyhal_resource_inst_t CYBSP_I2S_TX_SD_obj;
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

extern const cy_stc_gpio_pin_config_t CYBSP_I2S_TX_SCK_config;

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
extern const cyhal_resource_inst_t CYBSP_I2S_TX_SCK_obj;
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

extern const cy_stc_gpio_pin_config_t CYBSP_I2S_TX_MCK_config;

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
extern const cyhal_resource_inst_t CYBSP_I2S_TX_MCK_obj;
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

extern const cy_stc_gpio_pin_config_t CYBSP_RS_SPI_MISO_config;

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
extern const cyhal_resource_inst_t CYBSP_RS_SPI_MISO_obj;
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

extern const cy_stc_gpio_pin_config_t CYBSP_RS_SPI_MOSI_config;

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
extern const cyhal_resource_inst_t CYBSP_RS_SPI_MOSI_obj;
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

extern const cy_stc_gpio_pin_config_t CYBSP_RS_SPI_CLK_config;

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
extern const cyhal_resource_inst_t CYBSP_RS_SPI_CLK_obj;
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

extern const cy_stc_gpio_pin_config_t CYBSP_QSPI_SS_config;

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
extern const cyhal_resource_inst_t CYBSP_QSPI_SS_obj;
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

extern const cy_stc_gpio_pin_config_t CYBSP_OSPI_RAM_D0_config;

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
extern const cyhal_resource_inst_t CYBSP_OSPI_RAM_D0_obj;
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

extern const cy_stc_gpio_pin_config_t CYBSP_OSPI_RAM_D1_config;

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
extern const cyhal_resource_inst_t CYBSP_OSPI_RAM_D1_obj;
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

extern const cy_stc_gpio_pin_config_t CYBSP_OSPI_RAM_D2_config;

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
extern const cyhal_resource_inst_t CYBSP_OSPI_RAM_D2_obj;
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

extern const cy_stc_gpio_pin_config_t CYBSP_OSPI_RAM_D3_config;

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
extern const cyhal_resource_inst_t CYBSP_OSPI_RAM_D3_obj;
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

extern const cy_stc_gpio_pin_config_t CYBSP_OSPI_RAM_D4_config;

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
extern const cyhal_resource_inst_t CYBSP_OSPI_RAM_D4_obj;
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

extern const cy_stc_gpio_pin_config_t CYBSP_OSPI_RAM_D5_config;

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
extern const cyhal_resource_inst_t CYBSP_OSPI_RAM_D5_obj;
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

extern const cy_stc_gpio_pin_config_t CYBSP_OSPI_RAM_D6_config;

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
extern const cyhal_resource_inst_t CYBSP_OSPI_RAM_D6_obj;
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

extern const cy_stc_gpio_pin_config_t CYBSP_OSPI_RAM_D7_config;

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
extern const cyhal_resource_inst_t CYBSP_OSPI_RAM_D7_obj;
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

extern const cy_stc_gpio_pin_config_t CYBSP_WIFI_WL_REG_ON_config;

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
extern const cyhal_resource_inst_t CYBSP_WIFI_WL_REG_ON_obj;
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

extern const cy_stc_gpio_pin_config_t CYBSP_DEBUG_UART_RX_config;

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
extern const cyhal_resource_inst_t CYBSP_DEBUG_UART_RX_obj;
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

extern const cy_stc_gpio_pin_config_t CYBSP_DEBUG_UART_TX_config;

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
extern const cyhal_resource_inst_t CYBSP_DEBUG_UART_TX_obj;
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

extern const cy_stc_gpio_pin_config_t CYBSP_SDHC_CMD_config;

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
extern const cyhal_resource_inst_t CYBSP_SDHC_CMD_obj;
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

extern const cy_stc_gpio_pin_config_t CYBSP_SDHC_CLK_config;

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
extern const cyhal_resource_inst_t CYBSP_SDHC_CLK_obj;
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

extern const cy_stc_gpio_pin_config_t CYBSP_USER_BTN3_config;

#define CYBSP_SW5_config CYBSP_USER_BTN3_config

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
extern const cyhal_resource_inst_t CYBSP_USER_BTN3_obj;
#define CYBSP_SW5_obj CYBSP_USER_BTN3_obj
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

extern const cy_stc_gpio_pin_config_t CYBSP_SDHC_IO0_config;

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
extern const cyhal_resource_inst_t CYBSP_SDHC_IO0_obj;
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

extern const cy_stc_gpio_pin_config_t CYBSP_EXT_CLK_config;

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
extern const cyhal_resource_inst_t CYBSP_EXT_CLK_obj;
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

extern const cy_stc_gpio_pin_config_t CYBSP_SDHC_IO1_config;

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
extern const cyhal_resource_inst_t CYBSP_SDHC_IO1_obj;
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

extern const cy_stc_gpio_pin_config_t CYBSP_SDHC_IO2_config;

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
extern const cyhal_resource_inst_t CYBSP_SDHC_IO2_obj;
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

extern const cy_stc_gpio_pin_config_t CYBSP_SDHC_IO3_config;

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
extern const cyhal_resource_inst_t CYBSP_SDHC_IO3_obj;
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

extern const cy_stc_gpio_pin_config_t CYBSP_I2C_SCL_config;

#define CYBSP_I2C_SCL_1V8_config CYBSP_I2C_SCL_config

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
extern const cyhal_resource_inst_t CYBSP_I2C_SCL_obj;
#define CYBSP_I2C_SCL_1V8_obj CYBSP_I2C_SCL_obj
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

extern const cy_stc_gpio_pin_config_t CYBSP_I2C_SDA_config;

#define CYBSP_I2C_SDA_1V8_config CYBSP_I2C_SDA_config

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
extern const cyhal_resource_inst_t CYBSP_I2C_SDA_obj;
#define CYBSP_I2C_SDA_1V8_obj CYBSP_I2C_SDA_obj
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

extern const cy_stc_gpio_pin_config_t CYBSP_BT_POWER_config;

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
extern const cyhal_resource_inst_t CYBSP_BT_POWER_obj;
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

extern const cy_stc_gpio_pin_config_t CYBSP_USER_BTN1_config;

#define CYBSP_USER_BTN_config CYBSP_USER_BTN1_config
#define CYBSP_SW3_config CYBSP_USER_BTN1_config

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
extern const cyhal_resource_inst_t CYBSP_USER_BTN1_obj;
#define CYBSP_USER_BTN_obj CYBSP_USER_BTN1_obj
#define CYBSP_SW3_obj CYBSP_USER_BTN1_obj
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

extern const cy_stc_gpio_pin_config_t CYBSP_PDM_CLK_config;

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
extern const cyhal_resource_inst_t CYBSP_PDM_CLK_obj;
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

extern const cy_stc_gpio_pin_config_t CYBSP_PDM_DATA_config;

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
extern const cyhal_resource_inst_t CYBSP_PDM_DATA_obj;
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

extern const cy_stc_gpio_pin_config_t CYBSP_USER_BTN2_config;

#define CYBSP_SW4_config CYBSP_USER_BTN2_config

#if defined (CY_USING_HAL) || (CY_USING_HAL_LITE)
extern const cyhal_resource_inst_t CYBSP_USER_BTN2_obj;
#define CYBSP_SW4_obj CYBSP_USER_BTN2_obj
#endif /* defined (CY_USING_HAL) || (CY_USING_HAL_LITE) */

void init_cycfg_pins(void);
void reserve_cycfg_pins(void);

#if defined(__cplusplus)
}
#endif /* defined(__cplusplus) */

#endif /* CYCFG_PINS_H */
